import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '@/features/auth/AuthContext';
import { colors } from '@/theme';

export default function SignInScreen() {
  const auth = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string>();
  const valid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()) && password.length >= 8;
  const submit = async (create: boolean) => { if (!valid) { setMessage('Enter a valid email and a password of at least 8 characters.'); return; } setBusy(true); setMessage(undefined); const result = create ? await auth.signUpWithEmail(email, password) : await auth.signInWithEmail(email, password); setMessage(result.message); setBusy(false); };
  const google = async () => { setBusy(true); setMessage(undefined); const result = await auth.signInWithGoogle(); setMessage(result.message); setBusy(false); };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.container}><View><Text style={styles.brand}>RUQEST</Text><Text style={styles.eyebrow}>YOUR JOURNEY STARTS HERE</Text><Text style={styles.title}>Move. Explore. Progress.</Text><Text style={styles.copy}>Your workouts remain local first, then securely build your progress and territorial influence.</Text></View><View style={styles.form}><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" onChangeText={setEmail} placeholder="Email" placeholderTextColor={colors.muted} style={styles.input} value={email} /><TextInput autoCapitalize="none" autoComplete="current-password" onChangeText={setPassword} placeholder="Password" placeholderTextColor={colors.muted} secureTextEntry style={styles.input} value={password} />{message ? <Text style={styles.message}>{message}</Text> : null}<Pressable disabled={busy} onPress={() => void submit(false)} style={styles.primary}>{busy ? <ActivityIndicator color={colors.background} /> : <Text style={styles.primaryText}>SIGN IN</Text>}</Pressable><Pressable disabled={busy} onPress={() => void submit(true)} style={styles.secondary}><Text style={styles.secondaryText}>CREATE ACCOUNT</Text></Pressable><View style={styles.divider}><View style={styles.line}/><Text style={styles.or}>OR</Text><View style={styles.line}/></View><Pressable disabled={busy} onPress={() => void google()} style={styles.google}><Text style={styles.googleMark}>G</Text><Text style={styles.googleText}>Continue with Google</Text></Pressable></View>{!auth.configured ? <Text style={styles.setup}>Ruqest services are unavailable in this build. Please install a configured build or contact the beta team.</Text> : null}</KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},container:{flex:1,justifyContent:'center',padding:28,gap:34},brand:{color:colors.lime,fontSize:13,fontWeight:'900',letterSpacing:4},eyebrow:{color:colors.cyan,fontSize:10,fontWeight:'900',letterSpacing:2,marginTop:28},title:{color:colors.text,fontSize:36,fontWeight:'900',marginTop:7},copy:{color:colors.muted,lineHeight:21,marginTop:9},form:{gap:12},input:{height:54,borderRadius:15,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:16},message:{color:colors.gold,fontSize:12,lineHeight:17},primary:{height:54,borderRadius:15,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.background,fontWeight:'900'},secondary:{height:50,borderRadius:15,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.text,fontWeight:'900'},divider:{flexDirection:'row',alignItems:'center',gap:12,marginVertical:3},line:{height:1,backgroundColor:colors.border,flex:1},or:{color:colors.muted,fontSize:9,fontWeight:'900'},google:{height:54,borderRadius:15,backgroundColor:'#F6F7F5',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12},googleMark:{color:'#4285F4',fontSize:18,fontWeight:'900'},googleText:{color:'#18201D',fontWeight:'800'},setup:{color:colors.muted,fontSize:10,textAlign:'center'}});
