import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Avatar } from '@/components/profile/Avatar';
import { relationshipLabel } from '@/features/social/socialRules';
import type { PublicPlayerProfile } from '@/features/auth/types';
import { friendshipRepository } from '@/services/backend/friendshipRepository';
import { profileRepository } from '@/services/backend/profileRepository';
import { colors } from '@/theme';

export default function PlayerProfile(){
 const{id}=useLocalSearchParams<{id:string}>();const[player,setPlayer]=useState<PublicPlayerProfile|null>(null);const[loading,setLoading]=useState(true);const[acting,setActing]=useState(false);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);try{setPlayer(await profileRepository.getPublic(id))}catch{setError('This player profile is unavailable.')}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);
 const run=async(operation:()=>Promise<void>)=>{setActing(true);try{await operation();setLoading(true);await load()}catch(e){Alert.alert('Could not update roster',e instanceof Error?e.message:'No changes were made.')}finally{setActing(false)}};
 const primary=()=>{if(!player)return;if(player.relationship_status==='none')void run(()=>friendshipRepository.sendRequest(player.id));else if(player.relationship_status==='incoming_pending'&&player.request_id)void run(()=>friendshipRepository.acceptRequest(player.request_id!));else if(player.relationship_status==='outgoing_pending'&&player.request_id)void run(()=>friendshipRepository.cancelRequest(player.request_id!));else if(player.relationship_status==='friends')Alert.alert('Remove friend?',`${player.display_name} will leave your roster.`,[{text:'Keep friend',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>void run(()=>friendshipRepository.removeFriend(player.id))}])};
 const block=()=>{if(!player)return;if(player.relationship_status==='blocked_by_me')void run(()=>friendshipRepository.unblockPlayer(player.id));else Alert.alert('Block player?',`This removes any request or friendship with ${player.display_name}.`,[{text:'Cancel',style:'cancel'},{text:'Block',style:'destructive',onPress:()=>void run(()=>friendshipRepository.blockPlayer(player.id))}])};
 if(loading)return <View style={s.loading}><ActivityIndicator color={colors.lime}/><Text style={s.muted}>LOADING PLAYER INTEL</Text></View>;if(!player)return <View style={s.loading}><Text style={s.muted}>{error??'PLAYER NOT FOUND'}</Text><Pressable onPress={()=>router.back()}><Text style={s.back}>GO BACK</Text></Pressable></View>;
 const status=relationshipLabel(player.relationship_status);const disabled=acting||player.relationship_status==='restricted';
 return <ScrollView contentContainerStyle={s.screen}><Avatar name={player.display_name} url={player.avatar_url} size={110}/><Text numberOfLines={1} style={s.name}>{player.display_name}</Text><Text style={s.username}>@{player.username}</Text>{player.level!=null?<Text style={s.level}>LEVEL {player.level}</Text>:null}<Text style={s.friends}>{player.friends_count} FRIENDS</Text>{player.bio?<Text style={s.bio}>{player.bio}</Text>:null}{player.preferred_activities?<View style={s.chips}>{player.preferred_activities.map(a=><Text key={a} style={s.chip}>{a.toUpperCase()}</Text>)}</View>:null}{player.city||player.region?<Text style={s.muted}>{[player.city,player.region].filter(Boolean).join(' · ')}</Text>:null}<View style={s.stats}>{[['DISTANCE',player.total_distance==null?'—':`${(player.total_distance/1000).toFixed(1)} km`],['ACTIVITIES',player.total_activities??'—'],['TERRITORIES',player.territories_count??'—'],['INFLUENCE',player.total_influence??'—']].map(([key,value])=><View key={key} style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{key}</Text></View>)}</View>{(player.relationship_status !== 'blocked_by_me') ?<Pressable accessibilityLabel={status} disabled={disabled} onPress={primary} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{acting?'UPDATING…':status}</Text></Pressable>:null}{(player.relationship_status !== 'restricted') ?<Pressable accessibilityLabel={player.relationship_status==='blocked_by_me'?'Unblock player':'Block player'} disabled={acting} onPress={block}><Text style={s.block}>{player.relationship_status==='blocked_by_me'?'UNBLOCK PLAYER':'BLOCK PLAYER'}</Text></Pressable>:null}<Text style={s.security}>Exact GPS routes, live location, and activity paths are never available on player profiles.</Text></ScrollView>
}
const s=StyleSheet.create({screen:{flexGrow:1,alignItems:'center',padding:24,paddingTop:60,backgroundColor:colors.background},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:12,backgroundColor:colors.background},back:{color:colors.cyan,fontWeight:'900'},name:{color:colors.text,fontSize:28,fontWeight:'900',marginTop:14,maxWidth:'100%'},username:{color:colors.cyan},level:{color:colors.background,backgroundColor:colors.lime,fontSize:10,fontWeight:'900',padding:6,borderRadius:10,marginTop:10},friends:{color:colors.gold,fontSize:10,fontWeight:'900',marginTop:9},bio:{color:colors.text,textAlign:'center',lineHeight:20,marginTop:18},chips:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:7,marginVertical:15},chip:{color:colors.lime,fontSize:9,fontWeight:'900',borderWidth:1,borderColor:colors.border,borderRadius:12,padding:7},muted:{color:colors.muted,marginTop:12},stats:{width:'100%',flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:25},stat:{width:'48.5%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:14},statValue:{color:colors.text,fontSize:18,fontWeight:'900'},statLabel:{color:colors.muted,fontSize:9,fontWeight:'900',marginTop:4},button:{width:'100%',backgroundColor:colors.lime,borderRadius:14,padding:15,alignItems:'center',marginTop:22},disabled:{opacity:.45},buttonText:{color:colors.background,fontWeight:'900'},block:{color:colors.danger,fontSize:10,fontWeight:'900',padding:18},security:{color:colors.muted,fontSize:11,marginTop:6,textAlign:'center'}});
