import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { ExplorationSummary } from '@/features/exploration/explorationRules';
import { formatDuration } from '@/features/activity/activityRules';
import { ACTIVITY_PAGE_SIZE, type StoredOutdoorActivity } from '@/services/storage/activityRepository';
import { colors } from '@/theme';
import { useDomains } from '@/features/domains/useDomains';

const Empty=({icon,title,copy}:{icon:React.ComponentProps<typeof Ionicons>['name'];title:string;copy:string})=><View style={s.empty}><Ionicons name={icon} color={colors.cyan} size={28}/><Text style={s.emptyTitle}>{title}</Text><Text style={s.copy}>{copy}</Text></View>;
export function ProfileActivities({items,loading,hasMore,loadingMore,pageError,onLoadMore}:{items:StoredOutdoorActivity[];loading:boolean;hasMore:boolean;loadingMore:boolean;pageError:string|null;onLoadMore:()=>void}){if(loading&&!items.length)return <Empty icon="time-outline" title="LOADING ACTIVITIES" copy="Reading completed activities saved on this device."/>;if(!items.length)return <Empty icon="footsteps-outline" title="NO ACTIVITIES YET" copy="Completed outdoor activities saved on this device will appear here."/>;return <View style={s.stack}><Text style={s.note}>RECENT ACTIVITIES · THIS DEVICE</Text>{items.map(item=><Pressable accessibilityRole="button" accessibilityLabel={`Open ${item.type} activity results`} key={item.clientActivityId} onPress={()=>router.push({pathname:'/activity/results',params:{activityId:item.id,type:item.type}})} style={s.card}><View style={s.row}><Text style={s.accent}>{item.type.toUpperCase()}</Text><Text style={[s.sync,item.syncStatus==='synced'&&s.confirmed]}>{item.syncStatus.toUpperCase()}</Text></View><Text style={s.value}>{((item.authoritativeDistanceMeters??item.distanceMeters)/1000).toFixed(2)} KM</Text><Text style={s.copy}>{new Date(item.endedAt).toLocaleDateString()} · {formatDuration(item.durationSeconds)}</Text></Pressable>)}{hasMore?<><Text style={s.pageError}>{pageError}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Show ${ACTIVITY_PAGE_SIZE} more activities`} disabled={loadingMore} onPress={onLoadMore} style={[s.button,loadingMore&&s.disabled]}><Text style={s.buttonText}>{loadingMore?'LOADING…':`SHOW ${ACTIVITY_PAGE_SIZE} MORE`}</Text></Pressable></>:null}</View>}
export function ProfileTerritories({summary,loading}:{summary:ExplorationSummary|null|undefined;loading:boolean}){const domains=useDomains();if(loading&&summary===undefined)return <Empty icon="map-outline" title="LOADING EXPLORATION" copy="Retrieving your authoritative exploration summary."/>;if(!summary)return <Empty icon="map-outline" title="NO EXPLORATION DATA" copy="Explore outdoors to discover zones and build territorial influence."/>;return <View style={s.stack}><View style={s.metrics}><Metric label="CONTROLLED" value={summary.zonesControlled}/><Metric label="DISCOVERED" value={summary.totalZonesDiscovered}/><Metric label="INFLUENCE" value={summary.totalInfluence}/></View><View style={s.domainPanel}><Text style={s.heading}>YOUR DOMAINS</Text><Text style={s.domainValue}>{domains?.domainCount?`LARGEST DOMAIN · ${domains.largestDomainSize} ZONES`:'Control adjacent territories to build your first connected Domain.'}</Text>{domains?.domainCount?<Text style={s.copy}>{domains.domainCount} DOMAINS · {domains.totalControlledZones} CONTROLLED</Text>:null}</View><Text style={s.heading}>WEEKLY EXPLORATION</Text>{summary.objectives.map(o=><View key={o.key} style={s.objective}><Text style={s.objectiveTitle}>{o.title.toUpperCase()}</Text><Text style={s.copy}>{Math.min(o.progress,o.target).toLocaleString()} / {o.target.toLocaleString()}</Text><Text style={o.rewardedAt?s.done:s.reward}>{o.rewardedAt?'COMPLETE':`+${o.coins} COINS`}</Text></View>)}<Pressable accessibilityRole="button" onPress={()=>router.push('/map')} style={s.button}><Text style={s.buttonText}>VIEW ON MAP</Text></Pressable></View>}
export function ProfileAchievements({summary,loading}:{summary:ExplorationSummary|null|undefined;loading:boolean}){if(loading&&summary===undefined)return <Empty icon="trophy-outline" title="LOADING ACHIEVEMENTS" copy="Checking your unlocked exploration achievements."/>;const achievements=[...(summary?.achievements??[])].sort((a,b)=>new Date(b.unlockedAt).getTime()-new Date(a.unlockedAt).getTime());if(!achievements.length)return <Empty icon="trophy-outline" title="NO ACHIEVEMENTS YET" copy="Achievements unlock through real exploration and territory progress."/>;return <View style={s.stack}>{achievements.map(a=><View key={a.key} style={[s.card,s.achievement]}><Ionicons name="trophy" color={colors.gold} size={23}/><View style={s.grow}><Text style={s.achievementTitle}>{a.title.toUpperCase()}</Text><Text style={s.copy}>{a.description}</Text><Text style={s.unlocked}>UNLOCKED {new Date(a.unlockedAt).toLocaleDateString()}</Text></View></View>)}</View>}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value.toLocaleString()}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({domainPanel:{padding:15,borderRadius:16,borderWidth:1,borderColor:colors.cyan,backgroundColor:colors.surface},domainValue:{color:colors.text,fontWeight:'900',marginTop:8},stack:{padding:14,gap:10},note:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.2},card:{padding:15,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},row:{flexDirection:'row',justifyContent:'space-between'},accent:{color:colors.cyan,fontSize:9,fontWeight:'900'},sync:{color:colors.gold,fontSize:8,fontWeight:'900'},confirmed:{color:colors.lime},value:{color:colors.text,fontWeight:'900',fontSize:22,marginTop:5},copy:{color:colors.muted,fontSize:10,lineHeight:16,marginTop:3},empty:{alignItems:'center',margin:14,padding:28,borderRadius:18,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},emptyTitle:{color:colors.text,fontWeight:'900',fontSize:15,marginTop:10},metrics:{flexDirection:'row',gap:7},metric:{flex:1,minWidth:0,padding:12,borderRadius:14,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},metricValue:{color:colors.text,fontSize:19,fontWeight:'900'},metricLabel:{color:colors.muted,fontSize:7,fontWeight:'900',marginTop:4},heading:{color:colors.cyan,fontWeight:'900',fontSize:10,letterSpacing:1.3,marginTop:10},objective:{padding:13,borderRadius:13,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},objectiveTitle:{color:colors.text,fontSize:10,fontWeight:'900'},reward:{position:'absolute',right:12,top:14,color:colors.gold,fontSize:8,fontWeight:'900'},done:{position:'absolute',right:12,top:14,color:colors.lime,fontSize:8,fontWeight:'900'},button:{minHeight:50,alignItems:'center',justifyContent:'center',borderRadius:14,borderWidth:1,borderColor:colors.cyan},buttonText:{color:colors.cyan,fontWeight:'900'},disabled:{opacity:.55},pageError:{color:colors.danger,textAlign:'center',fontSize:10},achievement:{flexDirection:'row',gap:13},grow:{flex:1},achievementTitle:{color:colors.text,fontWeight:'900'},unlocked:{color:colors.gold,fontSize:8,fontWeight:'900',marginTop:8}});
