const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {isCompleteActivityResponse,classifySyncFailure}=require('../.test-dist/features/activity/syncContract.js');
test('complete-activity contract requires authoritative inventory and territory fields',()=>{assert.equal(isCompleteActivityResponse({activityId:'a',distanceMeters:100,xpEarned:10,energyEarned:2,influenceEarned:1,territoryImpacts:[],loot:[]}),true);assert.equal(isCompleteActivityResponse({activityId:'a',distanceMeters:100,xpEarned:10,energyEarned:2}),false);assert.equal(classifySyncFailure(new Error('Backend contract mismatch: malformed activity response')).code,'BACKEND_VERSION_MISMATCH');});
test('sync failures have distinct actionable categories',()=>{assert.equal(classifySyncFailure(new Error('Network request failed')).code,'NETWORK_UNAVAILABLE');assert.equal(classifySyncFailure({status:401}).code,'AUTHENTICATION_FAILURE');assert.equal(classifySyncFailure({status:400,toString:()=> 'invalid route'}).code,'ACTIVITY_REJECTED');assert.equal(classifySyncFailure({status:503}).code,'SERVER_ERROR');});
test('one activity failure does not break the queue and success invalidates territory',()=>{const source=fs.readFileSync('src/services/backend/activitySyncService.ts','utf8');assert.doesNotMatch(source,/markFailed\([^;]+;\s*break/);assert.match(source,/if\(failure\.global\)break/);assert.match(source,/territoryRepository\.invalidate\(\)/);});
test('active session creation is atomic without holding an exclusive database lock',()=>{const source=fs.readFileSync('src/services/storage/activeActivityRepository.ts','utf8');assert.match(source,/INSERT INTO active_activity_sessions[\s\S]+WHERE NOT EXISTS \(SELECT 1 FROM active_activity_sessions\)/);assert.match(source,/result\.changes !== 1/);assert.match(source,/PRAGMA busy_timeout = 5000/);assert.doesNotMatch(source,/withExclusiveTransactionAsync/);assert.doesNotMatch(source,/INSERT OR REPLACE INTO active_activity_sessions/);});
test('live map uses accepted points, preserves route gaps, and minimize only navigates',()=>{const source=fs.readFileSync('src/app/activity/active.tsx','utf8');assert.match(source,/const points = engine\.accepted/);assert.match(source,/routeFeatureCollection\(points\)/);assert.match(fs.readFileSync('src/features/map/mapbox/routeGeoJson.ts','utf8'),/splitRouteAtGaps\(accepted\)/);assert.match(source,/MINIMIZE/);assert.match(source,/router\.replace\('\/map'\)/);});
test('history cards navigate to owner-scoped private route detail',()=>{const cards=fs.readFileSync('src/app/(tabs)/activities.tsx','utf8');const detail=fs.readFileSync('src/app/activity/results.tsx','utf8');assert.match(cards,/router\.push\(\{pathname:'\/activity\/results'/);assert.match(detail,/PRIVATE ROUTE/);assert.match(detail,/activityRepository\.find\(params\.activityId,user\.id\)/);});
test('server finalization writes the authoritative territory chain consumed by world regions',()=>{const finalizer=fs.readFileSync('supabase/migrations/202609190005_inventory_loot_v1.sql','utf8');const world=fs.readFileSync('supabase/migrations/202609190004_territory_engine_v2.sql','utf8');for(const table of ['activity_territory_impacts','influence_ledger','territory_influence'])assert.match(finalizer,new RegExp(`insert into public\\.${table}`));assert.match(world,/from public\.territory_influence/);assert.match(world,/st_unaryunion/i);});

test('boundary crossings preserve the global 100 meters per influence rule',()=>{const {validateAndCompute}=require('../.test-dist-edge/activity.js');const start=Date.parse('2026-09-20T12:00:00Z');const points=Array.from({length:17},(_,index)=>({latitude:-22.9698+index*10/110574,longitude:-46.9974,timestamp:new Date(start+index*3000).toISOString(),accuracy:5}));const result=validateAndCompute({clientActivityId:'boundary-allocation',type:'walking',startedAt:new Date(start).toISOString(),endedAt:new Date(start+60_000).toISOString(),acceptedRoutePoints:points});assert.equal(result.impacts.reduce((sum,item)=>sum+item.influenceEarned,0),Math.floor(result.distanceMeters/100));});
test('outdoor completion and sync require a connected positive-distance segment',()=>{const {activityGpsState,canFinishOutdoorActivity,hasSyncableOutdoorRoute}=require('../.test-dist/features/activity/tracking.js');const point={latitude:0,longitude:0,timestamp:1,accuracy:5};const moved={...point,latitude:.0001,timestamp:2};const broken={...moved,breakBefore:true};assert.equal(hasSyncableOutdoorRoute([]),false);assert.equal(hasSyncableOutdoorRoute([point]),false);assert.equal(hasSyncableOutdoorRoute([point,moved]),true);assert.equal(hasSyncableOutdoorRoute([point,broken]),false);assert.equal(hasSyncableOutdoorRoute([point,broken,{...broken,latitude:.0002,timestamp:3,breakBefore:false}]),true);assert.equal(activityGpsState({phase:'acquiring',accepted:[]}),'acquiring');assert.equal(activityGpsState({phase:'tracking',accepted:[point]}),'ready');assert.equal(activityGpsState({phase:'tracking',accepted:[point,broken]}),'ready');assert.equal(canFinishOutdoorActivity({phase:'tracking',accepted:[point,moved]}),true);const screen=fs.readFileSync('src/app/activity/active.tsx','utf8');assert.match(screen,/GPS ACQUIRING/);assert.doesNotMatch(screen,/CANCEL ACTIVITY/);assert.match(screen,/onPress=\{\(\)=>router\.replace\('\/map'\)\}/);assert.match(screen,/disabled=\{!canFinish\}/);});
test('authoritative completion refreshes the subscribed weekly summary',()=>{const sync=fs.readFileSync('src/services/backend/activitySyncService.ts','utf8');const weekly=fs.readFileSync('src/services/backend/weeklySummaryRepository.ts','utf8');const component=fs.readFileSync('src/components/WeeklyProgress.tsx','utf8');assert.match(sync,/weeklySummaryRepository\.refresh\(\)/);assert.match(sync,/hasSyncableOutdoorRoute\(activity\.route\)/);assert.match(weekly,/subscribe\(listener/);assert.match(component,/weeklySummaryRepository\.subscribe\(value=>/);});
test('legacy unsyncable activities become terminal local failures without retry UX',()=>{const sync=fs.readFileSync('src/services/backend/activitySyncService.ts','utf8');const repository=fs.readFileSync('src/services/storage/activityRepository.ts','utf8');const result=fs.readFileSync('src/app/activity/results.tsx','utf8');assert.match(sync,/markFailed\(activity\.id,'INSUFFICIENT_GPS_DATA'/);assert.match(repository,/last_sync_error_code,''\)<>'INSUFFICIENT_GPS_DATA'/);assert.match(result,/insufficientGps\?'NOT ENOUGH GPS DATA'/);assert.match(result,/!insufficientGps\?<Pressable/);});

test('weekly summary refreshes serialize and pending updates cannot overwrite newer state',()=>{const weekly=fs.readFileSync('src/services/backend/weeklySummaryRepository.ts','utf8');const component=fs.readFileSync('src/components/WeeklyProgress.tsx','utf8');assert.match(weekly,/refreshQueue\.then\(fetchSummary\)/);assert.match(weekly,/notify\(value\)/);assert.doesNotMatch(weekly,/subscribe\(listener:Listener\)\{[^}]*fetchSummary/s);assert.doesNotMatch(component,/weeklySummaryRepository\.get\(/);assert.match(component,/pendingRequest=useRef\(0\)/);assert.match(component,/request===pendingRequest\.current/);assert.equal((component.match(/weeklySummaryRepository\.refresh\(\)/g)??[]).length,1);assert.doesNotMatch(component,/activityRepository\.subscribe\([^)]*weeklySummaryRepository/s);});
