const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const edge=require('../.test-dist-edge/activity.js');
const valid=()=>({clientActivityId:'test-activity-1',type:'walking',startedAt:'2026-09-18T10:00:00.000Z',endedAt:'2026-09-18T10:01:00.000Z',acceptedRoutePoints:[{latitude:-23.5505,longitude:-46.6333,timestamp:'2026-09-18T10:00:00.000Z',accuracy:8},{latitude:-23.5504,longitude:-46.6333,timestamp:'2026-09-18T10:00:20.000Z',accuracy:8}]});
test('server territory test vectors match deterministic client grid',()=>{assert.deepEqual(edge.territoryCoordinatesAt(0,0),{q:0,r:-0});assert.equal(edge.territoryId(-11040,-9469),'local--11040--9469');});
test('route GeoJSON is longitude then latitude and ignores body user_id',()=>{const body=valid();body.user_id='attacker-choice';const result=edge.validateAndCompute(body);assert.deepEqual(result.route.coordinates[0][0],[-46.6333,-23.5505]);assert.equal('user_id' in result,false);});
test('invalid coordinates are rejected',()=>{const body=valid();body.acceptedRoutePoints[1].latitude=91;assert.throws(()=>edge.validateAndCompute(body),/coordinate/);});
test('impossible route speed is rejected',()=>{const body=valid();body.acceptedRoutePoints[1]={latitude:-22,longitude:-46,timestamp:'2026-09-18T10:00:01.000Z',accuracy:5};assert.throws(()=>edge.validateAndCompute(body),/speed/);});
test('long segments allocate distance across every crossed atomic territory',()=>{const body=valid();body.endedAt='2026-09-18T10:10:00.000Z';body.acceptedRoutePoints[1]={latitude:-23.5505,longitude:-46.6233,timestamp:'2026-09-18T10:10:00.000Z',accuracy:5};const result=edge.validateAndCompute(body);assert.ok(result.impacts.length>1);const allocated=result.impacts.reduce((sum,item)=>sum+item.distanceMeters,0);assert.ok(Math.abs(allocated-result.distanceMeters)<.001);assert.equal(result.impacts.reduce((sum,item)=>sum+item.influenceEarned,0),result.territories.reduce((sum,territory)=>sum+result.impacts.find(item=>item.territoryId===territory.id).influenceEarned,0));});
test('schema protects private routes, economy writes, ledger, and atomic idempotency',()=>{const sql=fs.readFileSync('supabase/migrations/202609180001_secure_world_v1.sql','utf8');assert.match(sql,/activities_select_own/);assert.doesNotMatch(sql,/policy .*activities.*insert/i);assert.doesNotMatch(sql,/policy .*player_progress.*update/i);assert.doesNotMatch(sql,/policy .*territory_influence.*(insert|update)/i);assert.doesNotMatch(sql,/policy .*influence_ledger.*insert/i);assert.match(sql,/unique\(user_id,client_activity_id\)/i);assert.match(sql,/finalize_activity_transaction/);assert.match(sql,/grant execute[^;]+service_role/i);assert.match(sql,/revoke all[^;]+authenticated/i);});
test('edge function requires auth and derives user from verified JWT',()=>{const source=fs.readFileSync('supabase/functions/complete-activity/index.ts','utf8');assert.match(source,/Authentication required/);assert.match(source,/authClient\.auth\.getUser/);assert.match(source,/p_user_id:user\.id/);});
