const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const edge=require('../.test-dist-edge/activity.js');
const valid=()=>({clientActivityId:'test-activity-1',type:'walking',startedAt:'2026-09-18T10:00:00.000Z',endedAt:'2026-09-18T10:01:00.000Z',acceptedRoutePoints:[{latitude:-23.5505,longitude:-46.6333,timestamp:'2026-09-18T10:00:00.000Z',accuracy:8},{latitude:-23.5504,longitude:-46.6333,timestamp:'2026-09-18T10:00:20.000Z',accuracy:8}]});
test('server territory test vectors match deterministic client grid',()=>{assert.deepEqual(edge.territoryCoordinatesAt(0,0),{q:0,r:-0});assert.equal(edge.territoryId(-11040,-9469),'local--11040--9469');});
test('route GeoJSON is longitude then latitude and ignores body user_id',()=>{const body=valid();body.user_id='attacker-choice';const result=edge.validateAndCompute(body);assert.deepEqual(result.route.coordinates[0][0],[-46.6333,-23.5505]);assert.equal('user_id' in result,false);});
test('invalid coordinates are rejected',()=>{const body=valid();body.acceptedRoutePoints[1].latitude=91;assert.throws(()=>edge.validateAndCompute(body),/coordinate/);});
test('impossible route speed is rejected',()=>{const body=valid();body.acceptedRoutePoints[1]={latitude:-22,longitude:-46,timestamp:'2026-09-18T10:00:01.000Z',accuracy:5};assert.throws(()=>edge.validateAndCompute(body),/speed/);});
test('long segments allocate distance across every crossed atomic territory',()=>{const body=valid();body.endedAt='2026-09-18T10:10:00.000Z';body.acceptedRoutePoints[1]={latitude:-23.5505,longitude:-46.6233,timestamp:'2026-09-18T10:10:00.000Z',accuracy:5};const result=edge.validateAndCompute(body);assert.ok(result.impacts.length>1);const allocated=result.impacts.reduce((sum,item)=>sum+item.distanceMeters,0);assert.ok(Math.abs(allocated-result.distanceMeters)<.001);assert.equal(result.impacts.reduce((sum,item)=>sum+item.influenceEarned,0),result.territories.reduce((sum,territory)=>sum+result.impacts.find(item=>item.territoryId===territory.id).influenceEarned,0));});
test('schema protects private routes, economy writes, ledger, and atomic idempotency',()=>{const sql=fs.readFileSync('supabase/migrations/202609180001_secure_world_v1.sql','utf8');assert.match(sql,/activities_select_own/);assert.doesNotMatch(sql,/policy .*activities.*insert/i);assert.doesNotMatch(sql,/policy .*player_progress.*update/i);assert.doesNotMatch(sql,/policy .*territory_influence.*(insert|update)/i);assert.doesNotMatch(sql,/policy .*influence_ledger.*insert/i);assert.match(sql,/unique\(user_id,client_activity_id\)/i);assert.match(sql,/finalize_activity_transaction/);assert.match(sql,/grant execute[^;]+service_role/i);assert.match(sql,/revoke all[^;]+authenticated/i);});
test('edge function requires auth and derives user from verified JWT',()=>{const source=fs.readFileSync('supabase/functions/complete-activity/index.ts','utf8');assert.match(source,/Authentication required/);assert.match(source,/authClient\.auth\.getUser/);assert.match(source,/p_user_id:user\.id/);});

const routeHotfixMigration=()=>fs.readFileSync('supabase/migrations/202609250003_fix_activity_route_multilinestring.sql','utf8');
test('continuous routes use one valid MultiLineString segment',()=>{const body=valid();const result=edge.validateAndCompute(body);assert.equal(result.route.type,'MultiLineString');assert.equal(result.route.coordinates.length,1);assert.equal(result.route.coordinates[0].length,2);});
test('breakBefore creates disconnected MultiLineString segments without cross-gap distance',()=>{const body=valid();body.endedAt='2026-09-18T10:04:00.000Z';body.acceptedRoutePoints=[{latitude:-23.5505,longitude:-46.6333,timestamp:'2026-09-18T10:00:00.000Z',accuracy:8},{latitude:-23.5504,longitude:-46.6333,timestamp:'2026-09-18T10:01:00.000Z',accuracy:8},{latitude:-23.5405,longitude:-46.6333,timestamp:'2026-09-18T10:03:00.000Z',accuracy:8,breakBefore:true},{latitude:-23.5404,longitude:-46.6333,timestamp:'2026-09-18T10:04:00.000Z',accuracy:8}];const result=edge.validateAndCompute(body);assert.equal(result.route.type,'MultiLineString');assert.deepEqual(result.route.coordinates.map(segment=>segment.length),[2,2]);const connectedDistance=edge.distanceMeters(body.acceptedRoutePoints[0],body.acceptedRoutePoints[1])+edge.distanceMeters(body.acceptedRoutePoints[2],body.acceptedRoutePoints[3]);assert.ok(Math.abs(result.distanceMeters-connectedDistance)<.001);assert.ok(result.distanceMeters<50);});
test('route hotfix converts LineStrings and stores MultiLineStrings with total nested point count',()=>{const sql=routeHotfixMigration();assert.match(sql,/alter column route type extensions\.geometry\(MultiLineString,4326\)/i);assert.match(sql,/extensions\.st_multi\(route\)/i);assert.match(sql,/extensions\.st_geomfromgeojson\(p_route\)/i);assert.match(sql,/sum\(jsonb_array_length\(segment\)\)/i);const coordinates=[[[1,2],[3,4]],[[5,6],[7,8],[9,10]]];assert.equal(coordinates.reduce((total,segment)=>total+segment.length,0),5);});
test('route hotfix preserves both duplicate finalization paths and server-only execution',()=>{const sql=routeHotfixMigration();assert.match(sql,/if found then[\s\S]+?'duplicate',true/i);assert.match(sql,/exception when unique_violation[\s\S]+?'duplicate',true/i);assert.match(sql,/'duplicate',false/i);assert.match(sql,/grant execute[^;]+service_role/i);assert.match(sql,/revoke all[^;]+authenticated/i);});
test('finalization failures are logged by stage while the client response stays generic',()=>{const source=fs.readFileSync('supabase/functions/complete-activity/index.ts','utf8');assert.match(source,/console\.error\([^;]+\{stage,message,code\}/);assert.match(source,/catch\(error\)\{logFinalizationError\(stage,error\)/);assert.match(source,/error:'Activity finalization failed',code:'SERVER_ERROR'/);assert.doesNotMatch(source,/console\.error\([^\n]*(authorization|serviceKey|computed\.route)/i);});
