const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {territoryFeatureCollection,resolveTerritoryTap}=require('../.test-dist/features/map/mapbox/territoryGeoJson.js');
const {routeFeatureCollection,routeBounds}=require('../.test-dist/features/map/mapbox/routeGeoJson.js');
const root=path.join(__dirname,'..');
const region=(geometryType,polygons,extra={})=>({id:'region-1',ownerUserId:'me',ownerDisplayName:'Runner',ownerInfluencePoints:8,totalInfluencePoints:10,myInfluencePoints:8,controlPercentage:80,territoryCount:2,status:'owned',geometryType,polygons,source:'server',...extra});
test('Mapbox package/plugin exist and legacy production renderer is retired',()=>{const pkg=require('../package.json');assert.equal(pkg.dependencies['@rnmapbox/maps'],'10.2.10');assert.equal(pkg.dependencies.debounce,'1.2.1');assert.equal(pkg.dependencies['@turf/helpers'],'6.5.0');assert.equal(pkg.dependencies['@turf/along'],'6.5.0');assert.equal(pkg.dependencies['@turf/distance'],'6.5.0');assert.equal(pkg.dependencies['react-native-maps'],undefined);assert.match(fs.readFileSync(path.join(root,'app.config.js'),'utf8'),/@rnmapbox\/maps/);for(const file of walk(path.join(root,'src')))assert.doesNotMatch(fs.readFileSync(file,'utf8'),/react-native-maps/)});
test('Mapbox plugin preserves config and consumes only the build-secret environment variable',()=>{const previous=process.env.RNMAPBOX_MAPS_DOWNLOAD_TOKEN;process.env.RNMAPBOX_MAPS_DOWNLOAD_TOKEN='test-download-token';delete require.cache[require.resolve('../app.config.js')];const configured=require('../app.config.js')({config:{name:'CONQUEST',android:{package:'game.conquest'},plugins:['expo-router']}});if(previous===undefined)delete process.env.RNMAPBOX_MAPS_DOWNLOAD_TOKEN;else process.env.RNMAPBOX_MAPS_DOWNLOAD_TOKEN=previous;assert.equal(configured.name,'CONQUEST');assert.equal(configured.android.package,'game.conquest');assert.deepEqual(configured.plugins[0],'expo-router');assert.deepEqual(configured.plugins[1],['@rnmapbox/maps',{RNMapboxMapsImpl:'mapbox',RNMapboxMapsDownloadToken:'test-download-token'}]);const source=fs.readFileSync(path.join(root,'app.config.js'),'utf8');assert.match(source,/process\.env\.RNMAPBOX_MAPS_DOWNLOAD_TOKEN/);assert.doesNotMatch(source,/EXPO_PUBLIC_RNMAPBOX|EXPO_PUBLIC_MAPBOX_DOWNLOAD/)});
test('runtime token remains public environment configuration and no Mapbox secret value is committed',()=>{const runtime=fs.readFileSync(path.join(root,'src/features/map/mapbox/mapboxConfig.ts'),'utf8');assert.match(runtime,/process\.env\.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN/);assert.doesNotMatch(runtime,/RNMAPBOX_MAPS_DOWNLOAD_TOKEN/);const files=[...walk(path.join(root,'src')),...walk(path.join(root,'docs')),path.join(root,'.env.example'),path.join(root,'app.config.js'),path.join(root,'eas.json'),path.join(root,'package.json'),path.join(root,'package-lock.json')];for(const file of files)assert.doesNotMatch(fs.readFileSync(file,'utf8'),/sk\.[A-Za-z0-9_-]{8,}/)});
test('Polygon and its holes remain valid GeoJSON',()=>{const outer=[{latitude:0,longitude:0},{latitude:0,longitude:2},{latitude:2,longitude:0},{latitude:0,longitude:0}],hole=[{latitude:.2,longitude:.2},{latitude:.2,longitude:.4},{latitude:.4,longitude:.2},{latitude:.2,longitude:.2}];const f=territoryFeatureCollection([region('Polygon',[{outer,holes:[hole]}])]).features[0];assert.equal(f.geometry.type,'Polygon');assert.equal(f.geometry.coordinates.length,2);assert.equal(f.properties.regionId,'region-1');assert.equal(f.properties.source,'server');assert.equal('route' in f.properties,false)});
test('MultiPolygon is retained and territory taps resolve model',()=>{const ring=[{latitude:0,longitude:0},{latitude:0,longitude:1},{latitude:1,longitude:0},{latitude:0,longitude:0}];const r=region('MultiPolygon',[{outer:ring,holes:[]},{outer:ring.map(p=>({...p,longitude:p.longitude+3})),holes:[]}]);const collection=territoryFeatureCollection([r]);assert.equal(collection.features[0].geometry.type,'MultiPolygon');assert.equal(collection.features[0].geometry.coordinates.length,2);assert.equal(resolveTerritoryTap([r],'region-1'),r)});
test('rival visuals are deterministic and ownerless contested is safe',()=>{const rival=region('Polygon',[],{ownerUserId:'rival',status:'rival'});assert.equal(territoryFeatureCollection([rival]).features[0].properties.renderFillColor,territoryFeatureCollection([rival]).features[0].properties.renderFillColor);assert.doesNotThrow(()=>territoryFeatureCollection([region('Polygon',[],{ownerUserId:null,status:'contested'})]))});
test('private route only uses accepted input, keeps gaps, and computes fit bounds',()=>{const points=[{latitude:1,longitude:2,timestamp:1},{latitude:2,longitude:3,timestamp:2},{latitude:8,longitude:9,timestamp:30,breakBefore:true},{latitude:9,longitude:10,timestamp:31}];const route=routeFeatureCollection(points);assert.equal(route.features[0].geometry.type,'MultiLineString');assert.equal(route.features[0].geometry.coordinates.length,2);assert.deepEqual(routeBounds(points),{northEast:[10,9],southWest:[2,1]})});
test('renderer uses one territory ShapeSource and guarded development grid',()=>{const source=fs.readFileSync(path.join(root,'src/features/map/ConquestMap.tsx'),'utf8');assert.match(source,/ShapeSource id="conquest-world-regions"/);assert.match(source,/territoryGridDebugEnabled\(__DEV__,process\.env\.EXPO_PUBLIC_ENABLE_TERRITORY_GRID_DEBUG\)/);assert.match(source,/if\(!bounds\|\|!user\|\|locationDenied\)return/);assert.match(source,/setTimeout\(.*400/)});
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]).filter(f=>/\.(ts|tsx|md)$/.test(f))}
