const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {TERRITORY_DETAIL_MIN_ZOOM,WORLD_VIEWPORT_MAX_DEGREES,territoryDetailEnabled,isValidWorldViewport,paddedTerritoryViewport,viewportContains,isLatestTerritoryRequest,selectedTerritoryFilter}=require('../.test-dist/features/map/mapPerformance.js');

test('territory LOD starts at the centralized detail zoom',()=>{assert.equal(TERRITORY_DETAIL_MIN_ZOOM,14);assert.equal(territoryDetailEnabled(13.999),false);assert.equal(territoryDetailEnabled(14),true);assert.equal(territoryDetailEnabled(15),true);});
test('viewport validation and padding honor geographic and server limits',()=>{assert.equal(isValidWorldViewport({west:1,south:1,east:1,north:2}),false);assert.equal(isValidWorldViewport({west:-181,south:0,east:-180.9,north:.1}),false);const padded=paddedTerritoryViewport({west:179.9,south:84.9,east:180,north:85});assert.ok(padded);assert.ok(padded.west>=-180&&padded.east<=180&&padded.south>=-85&&padded.north<=85);assert.ok(padded.east-padded.west<=WORLD_VIEWPORT_MAX_DEGREES);assert.ok(padded.north-padded.south<=WORLD_VIEWPORT_MAX_DEGREES);assert.equal(paddedTerritoryViewport({west:0,south:0,east:.251,north:.1}),null);});
test('loaded viewport containment skips small pans and rejects escaped views',()=>{const loaded={west:0,south:0,east:.2,north:.2};assert.equal(viewportContains(loaded,{west:.02,south:.02,east:.18,north:.18}),true);assert.equal(viewportContains(loaded,{west:.03,south:.03,east:.21,north:.18}),false);assert.equal(viewportContains(null,{west:.02,south:.02,east:.18,north:.18}),false);});
test('request generations reject late responses',()=>{assert.equal(isLatestTerritoryRequest(16,16),true);assert.equal(isLatestTerritoryRequest(15,16),false);});
test('selection filter identifies one region and zoom-out releases geometry and selection',()=>{assert.deepEqual(selectedTerritoryFilter('zone-a'),['==',['get','regionId'],'zone-a']);const source=fs.readFileSync('src/features/map/ConquestMap.tsx','utf8');assert.match(source,/setRegions\(\[\]\)/);assert.match(source,/onTerritorySelectionChange\(null\)/);assert.match(source,/if \(!territoryDetail && detailWasEnabled\.current\) disableTerritoryDetail\(\)/);assert.match(source,/void requestViewport\(latestViewport\.current, state\.properties\.zoom\)/);});
test('map performance migration keeps contract, spatial operator, hard limit, and visible-first query',()=>{const sql=fs.readFileSync('supabase/migrations/202609250002_map_performance_v1.sql','utf8');for(const field of ['region_id text','zone_name text','owner_user_id uuid','owner_display_name text','geometry jsonb','total_influence bigint','owner_influence bigint','my_influence bigint','control_percentage double precision','territory_count bigint','status text'])assert.ok(sql.includes(field),field);assert.match(sql,/visible_territories as materialized/);assert.ok(sql.indexOf('visible_territories as materialized')<sql.indexOf('relevant_influence as'));assert.match(sql,/OPERATOR\(extensions\.&&\)/);assert.match(sql,/t\.geometry as territory_geometry/);assert.match(sql,/limit 2000/i);assert.doesNotMatch(sql,/activities\.route|raw GPS data[\s\S]*select/i);});
test('existing GiST geometry index remains additive and influence primary key serves visible joins',()=>{const base=fs.readFileSync('supabase/migrations/202609190004_territory_engine_v2.sql','utf8');const schema=fs.readFileSync('supabase/migrations/202609180001_secure_world_v1.sql','utf8');assert.match(base,/territories_geometry_gix on public\.territories using gist\(geometry\)/);assert.match(schema,/primary key\(territory_id,user_id\)/);});
test('cache remains bounded and server result is returned outside cache-write handling',()=>{const source=fs.readFileSync('src/services/backend/territoryRepository.ts','utf8');assert.match(source,/ORDER BY updated_at DESC LIMIT 24/);assert.match(source,/catch \(cacheError\)[\s\S]*return \{ regions: rows\.map/);});
test('world-region requests contain viewport only and no route or GPS payload',()=>{const source=fs.readFileSync('src/services/backend/territoryRepository.ts','utf8');assert.match(source,/supabase\.rpc\('get_world_regions', viewport\)/);assert.doesNotMatch(source,/accepted|route|latitude|longitude/);});
