const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {generateTerritories}=require('../.test-dist/features/territories/territoryGenerator.js');
const {territoryCandidatesForLocation,territoryGridDebugEnabled}=require('../.test-dist/features/territories/territoryMapData.js');
const {mapWorldRegion}=require('../.test-dist/features/territories/worldRegions.js');
const {rivalColor,territoryVisual}=require('../.test-dist/features/map/mapVisuals.js');
const origin={latitude:-22.9698,longitude:-46.9974};
const row={region_id:'r1',owner_user_id:'user-b',owner_display_name:'Runner',geometry:{type:'MultiPolygon',coordinates:[[[[-47,-23],[-46.99,-23],[-47,-22.99],[-47,-23]]],[[[-46.9,-23],[-46.89,-23],[-46.9,-22.99],[-46.9,-23]]]]},total_influence:100,owner_influence:70,my_influence:20,control_percentage:70,territory_count:3,status:'contested'};
test('atomic territory grid remains deterministic and internal',()=>{const a=generateTerritories(origin),b=generateTerritories(origin);assert.equal(a.length,19);assert.deepEqual(a.map(x=>x.id),b.map(x=>x.id));assert.ok(a.every(x=>x.boundary.length===6));});
test('location denial never generates a fallback world',()=>{assert.deepEqual(territoryCandidatesForLocation(origin,true),[]);});
test('MultiPolygon and holes remain distinct render polygons',()=>{const region=mapWorldRegion(row,'server');assert.equal(region.geometryType,'MultiPolygon');assert.equal(region.polygons.length,2);assert.equal(region.territoryCount,3);assert.equal(region.source,'server');});
test('influence points and percentage remain separate fields',()=>{const region=mapWorldRegion(row,'server');assert.equal(region.ownerInfluencePoints,70);assert.equal(region.controlPercentage,70);assert.equal(region.myInfluencePoints,20);});
test('current and rival colors are stable and organic edges are subtle',()=>{assert.equal(rivalColor('user-b'),rivalColor('user-b'));const rival=mapWorldRegion({...row,status:'rival',my_influence:0},'server');assert.deepEqual(territoryVisual(rival),{fillColor:`${rivalColor('user-b')}38`,strokeColor:`${rivalColor('user-b')}99`,strokeWidth:1});});
test('DEV grid requires both development and explicit flag',()=>{assert.equal(territoryGridDebugEnabled(true,'true'),true);assert.equal(territoryGridDebugEnabled(false,'true'),false);assert.equal(territoryGridDebugEnabled(true,undefined),false);});
test('production renderer consumes world regions, not generated atomic cells',()=>{const source=fs.readFileSync('src/features/map/ConquestMap.tsx','utf8');assert.match(source,/getWorldRegions/);assert.match(source,/debugGrid && atomicCells/);assert.doesNotMatch(source,/renderableTerritories/);});
test('empty world response creates no overlay',()=>{assert.deepEqual([].map(x=>mapWorldRegion(x,'server')),[]);});

test('V2 SQL defines safe deterministic ownership and geometry',()=>{const sql=fs.readFileSync('supabase/migrations/202609190004_territory_engine_v2.sql','utf8');for(const phrase of ['dense_rank()','when l.tied>1 then \'contested\'','when l.user_id=(select auth.uid()) then \'owned\'','extensions.st_unaryunion','extensions.st_makevalid','extensions.st_isvalid','extensions.st_multi','east-west > .25','territories_geometry_gix','territories_center_gix'])assert.ok(sql.includes(phrase),phrase);assert.doesNotMatch(sql,/activities\.route|\bemail\b|raw GPS/i);});
test('world response allowlist has no route or email',()=>{assert.deepEqual(Object.keys(row).sort(),['control_percentage','geometry','my_influence','owner_display_name','owner_influence','owner_user_id','region_id','status','territory_count','total_influence']);});
