import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ActivityFlowShell } from '@/components/ActivityFlowShell';
import { DISTANCE_MILESTONES, calculateTraversals, rewardsForDistance, type CompletedOutdoorActivity } from '@/features/activity/outdoorRules';
import { formatDuration, getSimulatedDistance, isActivityType } from '@/features/activity/activityRules';
import { createTrackingState, rollingGpsQuality, routeDistanceMeters, type OutdoorActivityType, type TrackingEngineState } from '@/features/activity/tracking';
import { usePois } from '@/features/poi/PoiContext';
import { BASE_OUTDOOR_XP_PER_KILOMETER } from '@/features/poi/config';
import { arenaPointsForTrainingPower, distanceMeters as distanceToPoi } from '@/features/poi/poiRules';
import { activities } from '@/mocks/game';
import { arenaRepository } from '@/services/storage/arenaRepository';
import { activityRepository } from '@/services/storage/activityRepository';
import { activeActivityRepository, loadTrackingState, type ActiveActivitySession } from '@/services/storage/activeActivityRepository';
import { startOutdoorTracking, stopOutdoorTracking } from '@/services/location/outdoorTrackingService';
import { colors } from '@/theme';

export default function ActiveActivityScreen() {
  const params = useLocalSearchParams<{ type?: string }>(); const type = isActivityType(params.type) ? params.type : 'walking';
  return type === 'indoor' ? <IndoorSession /> : <OutdoorSession type={type} />;
}

function OutdoorSession({ type }: { type: OutdoorActivityType }) {
  const activity = activities.find((item) => item.id === type) ?? activities[0]!;
  const [phase, setPhase] = useState<'ready' | 'permission' | 'tracking'>('ready'); const [starting, setStarting] = useState(false);
  const [session, setSession] = useState<ActiveActivitySession>(); const [engine, setEngine] = useState<TrackingEngineState>(() => createTrackingState(type)); const [now, setNow] = useState(Date.now());
  const { activePoi, presences } = usePois();
  const refresh = useCallback(async () => { const current = await activeActivityRepository.get(); if (!current || current.type !== type) return; setSession(current); setEngine(await loadTrackingState(current)); setPhase('tracking'); }, [type]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { if (phase !== 'tracking') return; const timer = setInterval(() => { setNow(Date.now()); void refresh(); }, 1000); return () => clearInterval(timer); }, [phase, refresh]);
  const points = engine.accepted; const distanceMeters = routeDistanceMeters(points); const next = DISTANCE_MILESTONES.find((item) => distanceMeters < item.distanceKm * 1000);
  const start = async () => { setStarting(true); const result = await startOutdoorTracking(type); setStarting(false); if (!result.ok) { setPhase('permission'); return; } await refresh(); };
  const finish = async () => {
    if (!session) return; await stopOutdoorTracking(); const endedAt = Date.now(); const traversals = calculateTraversals(points); const baseXp = Math.floor(distanceMeters / 1000 * BASE_OUTDOOR_XP_PER_KILOMETER);
    const specialZones = presences.filter(({ poi }) => poi.type === 'training_ground').map(({ poi }) => { const zoneDistance = points.slice(1).reduce((sum, point, index) => { if (point.breakBefore) return sum; const previous = points[index]!; const midpoint = { latitude: (previous.latitude + point.latitude) / 2, longitude: (previous.longitude + point.longitude) / 2 }; return distanceToPoi(midpoint, poi) <= poi.exitRadiusMeters ? sum + routeDistanceMeters([previous, point]) : sum; }, 0); const bonusXp = Math.floor(zoneDistance / 1000 * BASE_OUTDOOR_XP_PER_KILOMETER * 0.2); return { poiId: poi.id, poiName: poi.name, distanceMeters: zoneDistance, bonusXp }; }).filter((zone) => zone.distanceMeters > 0);
    const completed: CompletedOutdoorActivity = { id: session.id, type, startedAt: session.startedAt, endedAt, durationSeconds: Math.max(0, Math.floor((endedAt - session.startedAt) / 1000)), distanceMeters, route: points, traversals, influenceEarned: traversals.reduce((sum, item) => sum + item.influenceEarned, 0), unlockedRewards: rewardsForDistance(distanceMeters).map((item) => item.rarity), energyEarned: Math.floor(distanceMeters / 1000 * 24), xpEarned: baseXp + specialZones.reduce((sum, zone) => sum + zone.bonusXp, 0), specialZones };
    await activityRepository.save(completed); await activeActivityRepository.remove(session.id); router.replace({ pathname: '/activity/results', params: { type, activityId: completed.id } });
  };
  const recover = async () => { if (!session) return; const result = await startOutdoorTracking(session.type); if (result.ok) { await activeActivityRepository.markActive(session.id); await refresh(); } };
  const discard = async () => { if (!session) return; await stopOutdoorTracking(); await activeActivityRepository.remove(session.id); router.replace('/map'); };
  if (phase !== 'tracking') return <ActivityFlowShell eyebrow="OUTDOOR ACTIVITY" title={activity.label}><View style={styles.ready}><Ionicons name="navigate-circle" size={64} color={activity.color} /><Text style={styles.readyTitle}>{phase === 'permission' ? 'Location permission needed' : 'Ready to start?'}</Text><Text style={styles.readyCopy}>CONQUEST needs precise “Allow all the time” location access to record your fitness route while the screen is locked. Android will keep a visible activity notification.</Text><Text style={styles.gps}>Background GPS · High accuracy</Text><Pressable disabled={starting} onPress={() => void start()} style={styles.start}><Text style={styles.startText}>{starting ? 'STARTING GPS…' : 'START ACTIVITY'}</Text></Pressable></View></ActivityFlowShell>;
  if (session?.status === 'interrupted') return <ActivityFlowShell eyebrow="ACTIVITY RECOVERY" title={activity.label} canGoBack={false}><View style={styles.ready}><Ionicons name="warning-outline" size={58} color={colors.gold} /><Text style={styles.readyTitle}>Previous activity was interrupted.</Text><Text style={styles.readyCopy}>Your accepted route is safe. Android cannot continue location after a force-stop.</Text><Pressable onPress={() => void recover()} style={styles.start}><Text style={styles.startText}>RECOVER ACTIVITY</Text></Pressable><Pressable onPress={() => void finish()} style={styles.recoverySecondary}><Text style={styles.recoveryText}>FINISH WITH RECORDED DATA</Text></Pressable><Pressable onPress={() => void discard()} style={styles.recoverySecondary}><Text style={styles.recoveryText}>DISCARD</Text></Pressable></View></ActivityFlowShell>;
  const elapsed = Math.floor((now - (session?.startedAt ?? now)) / 1000); const activeGround = activePoi('training_ground'); const quality = rollingGpsQuality(engine);
  return <ActivityFlowShell eyebrow="GPS SESSION · LIVE" title={activity.label} canGoBack={false}><View style={styles.status}><View style={[styles.pulse, { backgroundColor: activity.color }]} /><Text style={styles.statusText}>{engine.phase === 'acquiring' ? 'ACQUIRING GPS…' : `BACKGROUND GPS · ${quality}`}</Text></View>{activeGround ? <View style={styles.boost}><Text style={styles.boostText}>TRAINING GROUND ACTIVE · +20% XP</Text></View> : null}<View style={styles.metric}><Text style={styles.metricLabel}>DURATION</Text><Text style={styles.metricValue}>{formatDuration(elapsed)}</Text><Text style={styles.distance}>{(distanceMeters / 1000).toFixed(2)} km</Text></View><View style={styles.secondary}><Metric value={`${Math.floor(distanceMeters / 1000 * 24)}`} label="ENERGY EARNED" /><View style={styles.divider} /><Metric value={next ? `${next.distanceKm} km` : 'Complete'} label={next ? `${next.rarity.toUpperCase()} NEXT` : 'ALL REWARDS'} /></View><View style={styles.safety}><Ionicons name="phone-portrait-outline" size={22} color={colors.cyan} /><Text style={styles.safetyText}>{engine.phase === 'acquiring' ? 'Hold briefly for a stable GPS fix. Distance starts only when GPS is ready.' : 'You can lock your screen. No interaction is needed until you finish.'}</Text></View><View style={styles.spacer} /><Pressable onPress={() => void finish()} style={styles.finish}><Ionicons name="stop" size={18} color={colors.text} /><Text style={styles.finishText}>Finish activity</Text></Pressable></ActivityFlowShell>;
}
function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.secondaryItem}><Text style={styles.secondaryValue}>{value}</Text><Text style={styles.secondaryLabel}>{label}</Text></View>; }
function IndoorSession() {
  const [ticks, setTicks] = useState(0); const [arenaPoints, setArenaPoints] = useState(0); const arenaUsed = useRef<{ id: string; name: string } | undefined>(undefined); const startedAt = useRef(Date.now()); const { activePoi } = usePois(); const arena = activePoi('arena'); const activePoiRef = useRef(activePoi); activePoiRef.current = activePoi;
  useEffect(() => { const timer = setInterval(() => { setTicks((value) => value + 1); const current = activePoiRef.current('arena'); if (current) { arenaUsed.current = current; setArenaPoints((value) => value + arenaPointsForTrainingPower(42, true)); } }, 1000); return () => clearInterval(timer); }, []);
  const finish = async () => { const safeTicks = Math.max(ticks, 1); const endedAt = Date.now(); const id = `${startedAt.current}-indoor`; let total: number | undefined; let rank: number | undefined; if (arenaUsed.current && arenaPoints > 0) { total = await arenaRepository.addPoints(arenaUsed.current.id, arenaPoints, id, endedAt); rank = (await arenaRepository.getLeaderboard(arenaUsed.current.id)).find((item) => item.isPlayer)?.rank; } await activityRepository.saveIndoor({ id, startedAt: startedAt.current, endedAt, durationSeconds: safeTicks * 60, trainingPower: safeTicks * 42, xpEarned: safeTicks * 18, energyEarned: safeTicks * 7, arenaId: arenaUsed.current?.id, arenaName: arenaUsed.current?.name, arenaPointsEarned: arenaPoints, arenaWeeklyTotal: total, arenaWeeklyRank: rank }); router.replace({ pathname: '/activity/results', params: { type: 'indoor', activityId: id } }); };
  return <ActivityFlowShell eyebrow="INDOOR SESSION · LIVE" title="Indoor"><View style={styles.metric}><Text style={styles.metricLabel}>DURATION</Text><Text style={styles.metricValue}>{formatDuration(ticks * 60)}</Text><Text style={styles.distance}>{Math.round(getSimulatedDistance('indoor', ticks))} TP</Text></View><View style={styles.secondary}><Metric value={arena ? 'ACTIVE' : 'PAUSED'} label={arena?.name ?? 'ARENA SCORING'} /><View style={styles.divider} /><Metric value={`${arenaPoints}`} label="ARENA POINTS" /></View><View style={styles.spacer} /><Pressable onPress={() => void finish()} style={styles.finish}><Text style={styles.finishText}>Finish activity</Text></Pressable></ActivityFlowShell>;
}
const styles = StyleSheet.create({ ready: { alignItems: 'center', marginTop: 45, padding: 22, borderRadius: 22, backgroundColor: colors.surface }, readyTitle: { color: colors.text, fontSize: 24, fontWeight: '900', marginTop: 12, textAlign: 'center' }, readyCopy: { color: colors.muted, textAlign: 'center', lineHeight: 20, marginTop: 8 }, gps: { color: colors.cyan, fontWeight: '800', marginTop: 22 }, start: { alignSelf: 'stretch', alignItems: 'center', marginTop: 18, padding: 18, borderRadius: 17, backgroundColor: colors.lime }, startText: { color: colors.background, fontWeight: '900' }, recoverySecondary: { alignSelf: 'stretch', alignItems: 'center', marginTop: 10, padding: 15, borderRadius: 15, borderWidth: 1, borderColor: colors.border }, recoveryText: { color: colors.text, fontWeight: '800', fontSize: 12 }, status: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', marginTop: 12, backgroundColor: colors.surface, borderRadius: 99, paddingHorizontal: 13, paddingVertical: 8 }, pulse: { width: 8, height: 8, borderRadius: 4, marginRight: 8 }, statusText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, boost: { alignSelf: 'center', marginTop: 8, paddingHorizontal: 11, paddingVertical: 6, borderRadius: 9, backgroundColor: '#B7E85A20', borderWidth: 1, borderColor: '#B7E85A60' }, boostText: { color: colors.lime, fontSize: 9, fontWeight: '900' }, metric: { alignItems: 'center', paddingVertical: 38 }, metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 2 }, metricValue: { color: colors.text, fontSize: 60, fontWeight: '300', fontVariant: ['tabular-nums'] }, distance: { color: colors.cyan, fontSize: 28, fontWeight: '900', marginTop: 5 }, secondary: { flexDirection: 'row', borderWidth: 1, borderColor: colors.border, borderRadius: 22, backgroundColor: colors.surface, paddingVertical: 20 }, secondaryItem: { flex: 1, alignItems: 'center', gap: 5 }, secondaryValue: { color: colors.text, fontWeight: '900', fontSize: 22 }, secondaryLabel: { color: colors.muted, fontWeight: '800', fontSize: 9 }, divider: { width: 1, backgroundColor: colors.border }, safety: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 18, padding: 16, borderRadius: 18, backgroundColor: '#0B2422' }, safetyText: { color: colors.muted, flex: 1, fontSize: 11, lineHeight: 17 }, spacer: { flex: 1, minHeight: 28 }, finish: { height: 58, borderRadius: 18, backgroundColor: colors.danger, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, finishText: { color: colors.text, fontSize: 16, fontWeight: '900' } });
