import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ActivityFlowShell } from '@/components/ActivityFlowShell';
import { formatDuration, getSimulatedDistance, isActivityType } from '@/features/activity/activityRules';
import { activities } from '@/mocks/game';
import { colors } from '@/theme';

export default function ActiveActivityScreen() {
  const params = useLocalSearchParams<{ type?: string }>();
  const type = isActivityType(params.type) ? params.type : 'walking';
  const activity = useMemo(() => activities.find((item) => item.id === type) ?? activities[0]!, [type]);
  const [ticks, setTicks] = useState(0);
  useEffect(() => { const timer = setInterval(() => setTicks((value) => value + 1), 1000); return () => clearInterval(timer); }, []);
  const elapsed = ticks * 60;
  const distance = getSimulatedDistance(type, ticks);
  const finish = () => router.replace({ pathname: '/activity/results', params: { type, ticks: Math.max(ticks, 1).toString() } });
  return <ActivityFlowShell eyebrow="MOCK SESSION · LIVE" title={activity.label}><View style={styles.status}><View style={[styles.pulse, { backgroundColor: activity.color }]} /><Text style={styles.statusText}>SIMULATING PROGRESS · 60× SPEED</Text></View><View style={styles.metric}><Text style={styles.metricLabel}>DURATION</Text><Text accessibilityLabel={`${Math.floor(elapsed / 60)} minutes elapsed`} style={styles.metricValue}>{formatDuration(elapsed)}</Text><Text style={styles.metricHint}>Each real second simulates one active minute</Text></View><View style={styles.secondary}><View style={styles.secondaryItem}><Ionicons name={type === 'indoor' ? 'barbell-outline' : 'navigate-outline'} size={22} color={activity.color} /><Text style={styles.secondaryValue}>{type === 'indoor' ? ticks * 42 : distance.toFixed(2)}</Text><Text style={styles.secondaryLabel}>{type === 'indoor' ? 'TRAINING POWER' : 'KILOMETERS'}</Text></View><View style={styles.divider} /><View style={styles.secondaryItem}><Ionicons name="flash-outline" size={22} color={colors.gold} /><Text style={styles.secondaryValue}>{type === 'indoor' ? ticks * 7 : Math.round(distance * 24)}</Text><Text style={styles.secondaryLabel}>ENERGY EARNED</Text></View></View><View style={styles.safety}><Ionicons name="phone-portrait-outline" size={22} color={colors.cyan} /><View style={styles.safetyCopy}><Text style={styles.safetyTitle}>Keep moving. We’ll track the rest.</Text><Text style={styles.safetyText}>In a real session, you should not interact with your phone while moving.</Text></View></View><View style={styles.spacer} /><Pressable accessibilityRole="button" onPress={finish} style={({ pressed }) => [styles.finish, pressed && styles.pressed]}><Ionicons name="stop" size={18} color={colors.text} /><Text style={styles.finishText}>Finish activity</Text></Pressable></ActivityFlowShell>;
}

const styles = StyleSheet.create({ status: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', marginTop: 12, backgroundColor: colors.surface, borderRadius: 99, paddingHorizontal: 13, paddingVertical: 8 }, pulse: { width: 8, height: 8, borderRadius: 4, marginRight: 8 }, statusText: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 0.7 }, metric: { alignItems: 'center', paddingVertical: 42 }, metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 2 }, metricValue: { color: colors.text, fontSize: 64, lineHeight: 74, fontWeight: '300', fontVariant: ['tabular-nums'] }, metricHint: { color: colors.muted, fontSize: 11 }, secondary: { flexDirection: 'row', borderWidth: 1, borderColor: colors.border, borderRadius: 22, backgroundColor: colors.surface, paddingVertical: 20 }, secondaryItem: { flex: 1, alignItems: 'center', gap: 5 }, secondaryValue: { color: colors.text, fontWeight: '900', fontSize: 24 }, secondaryLabel: { color: colors.muted, fontWeight: '800', fontSize: 9, letterSpacing: 0.8 }, divider: { width: 1, backgroundColor: colors.border }, safety: { flexDirection: 'row', marginTop: 18, padding: 16, borderRadius: 18, backgroundColor: '#0B2422' }, safetyCopy: { flex: 1, marginLeft: 12 }, safetyTitle: { color: colors.text, fontWeight: '800', fontSize: 13 }, safetyText: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 4 }, spacer: { flex: 1, minHeight: 35 }, finish: { height: 58, borderRadius: 18, backgroundColor: colors.danger, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, finishText: { color: colors.text, fontSize: 16, fontWeight: '900' }, pressed: { opacity: 0.75 } });
