import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ActivityFlowShell } from '@/components/ActivityFlowShell';
import { DISTANCE_MILESTONES, calculateTraversals, rewardsForDistance, type CompletedOutdoorActivity } from '@/features/activity/outdoorRules';
import { formatDuration, getSimulatedDistance, isActivityType } from '@/features/activity/activityRules';
import { assessPoint, gpsQuality, routeDistanceMeters, segmentDistanceMeters, type ActivityPoint, type OutdoorActivityType } from '@/features/activity/tracking';
import { usePois } from '@/features/poi/PoiContext';
import { BASE_OUTDOOR_XP_PER_KILOMETER, TRAINING_GROUND_XP_MULTIPLIER } from '@/features/poi/config';
import { arenaPointsForTrainingPower } from '@/features/poi/poiRules';
import { activities } from '@/mocks/game';
import { arenaRepository } from '@/services/storage/arenaRepository';
import { activityRepository } from '@/services/storage/activityRepository';
import { colors } from '@/theme';

export default function ActiveActivityScreen() {
  const params = useLocalSearchParams<{ type?: string }>(); const type = isActivityType(params.type) ? params.type : 'walking';
  return type === 'indoor' ? <IndoorSession /> : <OutdoorSession type={type} />;
}

function OutdoorSession({ type }: { type: OutdoorActivityType }) {
  const activity = activities.find((item) => item.id === type) ?? activities[0]!;
  const [phase, setPhase] = useState<'ready' | 'error' | 'tracking'>('ready'); const [starting, setStarting] = useState(false);
  const [points, setPoints] = useState<ActivityPoint[]>([]); const [startedAt, setStartedAt] = useState(0); const [now, setNow] = useState(Date.now());
  const { location, activePoi } = usePois(); const lastTimestamp = useRef(0); const groundDistance = useRef(0); const ground = useRef<{ id: string; name: string } | undefined>(undefined);
  useEffect(() => { if (phase !== 'tracking') return; const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, [phase]);
  useEffect(() => {
    if (phase !== 'tracking' || !location || location.timestamp <= lastTimestamp.current) return; lastTimestamp.current = location.timestamp;
    setPoints((accepted) => { if (!assessPoint(location, accepted.at(-1), type).accepted) return accepted; const previous = accepted.at(-1); const activeGround = activePoi('training_ground'); if (previous && activeGround) { groundDistance.current += segmentDistanceMeters(previous, location); ground.current = activeGround; } return [...accepted, location]; });
  }, [activePoi, location, phase, type]);
  const distanceMeters = useMemo(() => routeDistanceMeters(points), [points]); const accuracy = points.at(-1)?.accuracy; const next = DISTANCE_MILESTONES.find((item) => distanceMeters < item.distanceKm * 1000);
  const start = () => { setStarting(true); if (!location) { setPhase('error'); setStarting(false); return; } const time = Date.now(); setStartedAt(time); setNow(time); setPhase('tracking'); setStarting(false); };
  const finish = async () => {
    const endedAt = Date.now(); const traversals = calculateTraversals(points); const baseXp = Math.floor(distanceMeters / 1000 * BASE_OUTDOOR_XP_PER_KILOMETER); const bonusXp = Math.floor(groundDistance.current / 1000 * BASE_OUTDOOR_XP_PER_KILOMETER * (TRAINING_GROUND_XP_MULTIPLIER - 1));
    const completed: CompletedOutdoorActivity = { id: `${startedAt}-${type}`, type, startedAt, endedAt, durationSeconds: Math.max(0, Math.floor((endedAt - startedAt) / 1000)), distanceMeters, route: points, traversals, influenceEarned: traversals.reduce((sum, item) => sum + item.influenceEarned, 0), unlockedRewards: rewardsForDistance(distanceMeters).map((item) => item.rarity), energyEarned: Math.floor(distanceMeters / 1000 * 24), xpEarned: baseXp + bonusXp, specialZones: ground.current ? [{ poiId: ground.current.id, poiName: ground.current.name, distanceMeters: groundDistance.current, bonusXp }] : [] };
    await activityRepository.save(completed); router.replace({ pathname: '/activity/results', params: { type, activityId: completed.id } });
  };
  if (phase !== 'tracking') return <ActivityFlowShell eyebrow="OUTDOOR ACTIVITY" title={activity.label}><View style={styles.ready}><Ionicons name="navigate-circle" size={64} color={activity.color} /><Text style={styles.readyTitle}>{phase === 'error' ? 'GPS is not ready' : 'Ready to start?'}</Text><Text style={styles.readyCopy}>GPS will record your real route while this screen remains active.</Text><Text style={styles.gps}>Foreground GPS · High accuracy</Text><Pressable disabled={starting} onPress={start} style={styles.start}><Text style={styles.startText}>{starting ? 'STARTING GPS…' : 'START ACTIVITY'}</Text></Pressable></View></ActivityFlowShell>;
  const elapsed = Math.floor((now - startedAt) / 1000); const activeGround = activePoi('training_ground');
  return <ActivityFlowShell eyebrow="GPS SESSION · LIVE" title={activity.label} canGoBack={false}><View style={styles.status}><View style={[styles.pulse, { backgroundColor: activity.color }]} /><Text style={styles.statusText}>FOREGROUND GPS · {gpsQuality(accuracy).toUpperCase()}</Text></View>{activeGround ? <View style={styles.boost}><Text style={styles.boostText}>TRAINING GROUND ACTIVE · +20% XP</Text></View> : null}<View style={styles.metric}><Text style={styles.metricLabel}>DURATION</Text><Text style={styles.metricValue}>{formatDuration(elapsed)}</Text><Text style={styles.distance}>{(distanceMeters / 1000).toFixed(2)} km</Text></View><View style={styles.secondary}><Metric value={`${Math.floor(distanceMeters / 1000 * 24)}`} label="ENERGY EARNED" /><View style={styles.divider} /><Metric value={next ? `${next.distanceKm} km` : 'Complete'} label={next ? `${next.rarity.toUpperCase()} NEXT` : 'ALL REWARDS'} /></View><View style={styles.safety}><Ionicons name="phone-portrait-outline" size={22} color={colors.cyan} /><Text style={styles.safetyText}>Keep moving safely. No interaction is needed until you finish.</Text></View><View style={styles.spacer} /><Pressable onPress={() => void finish()} style={styles.finish}><Ionicons name="stop" size={18} color={colors.text} /><Text style={styles.finishText}>Finish activity</Text></Pressable></ActivityFlowShell>;
}
function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.secondaryItem}><Text style={styles.secondaryValue}>{value}</Text><Text style={styles.secondaryLabel}>{label}</Text></View>; }
function IndoorSession() {
  const [ticks, setTicks] = useState(0); const [arenaPoints, setArenaPoints] = useState(0); const arenaUsed = useRef<{ id: string; name: string } | undefined>(undefined); const startedAt = useRef(Date.now()); const { activePoi } = usePois(); const arena = activePoi('arena'); const activePoiRef = useRef(activePoi); activePoiRef.current = activePoi;
  useEffect(() => { const timer = setInterval(() => { setTicks((value) => value + 1); const current = activePoiRef.current('arena'); if (current) { arenaUsed.current = current; setArenaPoints((value) => value + arenaPointsForTrainingPower(42, true)); } }, 1000); return () => clearInterval(timer); }, []);
  const finish = async () => { const safeTicks = Math.max(ticks, 1); const endedAt = Date.now(); const id = `${startedAt.current}-indoor`; let total: number | undefined; let rank: number | undefined; if (arenaUsed.current && arenaPoints > 0) { total = await arenaRepository.addPoints(arenaUsed.current.id, arenaPoints, id, endedAt); rank = (await arenaRepository.getLeaderboard(arenaUsed.current.id)).find((item) => item.isPlayer)?.rank; } await activityRepository.saveIndoor({ id, startedAt: startedAt.current, endedAt, durationSeconds: safeTicks * 60, trainingPower: safeTicks * 42, xpEarned: safeTicks * 18, energyEarned: safeTicks * 7, arenaId: arenaUsed.current?.id, arenaName: arenaUsed.current?.name, arenaPointsEarned: arenaPoints, arenaWeeklyTotal: total, arenaWeeklyRank: rank }); router.replace({ pathname: '/activity/results', params: { type: 'indoor', activityId: id } }); };
  return <ActivityFlowShell eyebrow="INDOOR SESSION · LIVE" title="Indoor"><View style={styles.metric}><Text style={styles.metricLabel}>DURATION</Text><Text style={styles.metricValue}>{formatDuration(ticks * 60)}</Text><Text style={styles.distance}>{Math.round(getSimulatedDistance('indoor', ticks))} TP</Text></View><View style={styles.secondary}><Metric value={arena ? 'ACTIVE' : 'PAUSED'} label={arena?.name ?? 'ARENA SCORING'} /><View style={styles.divider} /><Metric value={`${arenaPoints}`} label="ARENA POINTS" /></View><View style={styles.spacer} /><Pressable onPress={() => void finish()} style={styles.finish}><Text style={styles.finishText}>Finish activity</Text></Pressable></ActivityFlowShell>;
}
const styles = StyleSheet.create({ ready: { alignItems: 'center', marginTop: 45, padding: 22, borderRadius: 22, backgroundColor: colors.surface }, readyTitle: { color: colors.text, fontSize: 24, fontWeight: '900', marginTop: 12 }, readyCopy: { color: colors.muted, textAlign: 'center', lineHeight: 20, marginTop: 8 }, gps: { color: colors.cyan, fontWeight: '800', marginTop: 22 }, start: { alignSelf: 'stretch', alignItems: 'center', marginTop: 18, padding: 18, borderRadius: 17, backgroundColor: colors.lime }, startText: { color: colors.background, fontWeight: '900' }, status: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', marginTop: 12, backgroundColor: colors.surface, borderRadius: 99, paddingHorizontal: 13, paddingVertical: 8 }, pulse: { width: 8, height: 8, borderRadius: 4, marginRight: 8 }, statusText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, boost: { alignSelf: 'center', marginTop: 8, paddingHorizontal: 11, paddingVertical: 6, borderRadius: 9, backgroundColor: '#B7E85A20', borderWidth: 1, borderColor: '#B7E85A60' }, boostText: { color: colors.lime, fontSize: 9, fontWeight: '900' }, metric: { alignItems: 'center', paddingVertical: 38 }, metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 2 }, metricValue: { color: colors.text, fontSize: 60, fontWeight: '300', fontVariant: ['tabular-nums'] }, distance: { color: colors.cyan, fontSize: 28, fontWeight: '900', marginTop: 5 }, secondary: { flexDirection: 'row', borderWidth: 1, borderColor: colors.border, borderRadius: 22, backgroundColor: colors.surface, paddingVertical: 20 }, secondaryItem: { flex: 1, alignItems: 'center', gap: 5 }, secondaryValue: { color: colors.text, fontWeight: '900', fontSize: 22 }, secondaryLabel: { color: colors.muted, fontWeight: '800', fontSize: 9 }, divider: { width: 1, backgroundColor: colors.border }, safety: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 18, padding: 16, borderRadius: 18, backgroundColor: '#0B2422' }, safetyText: { color: colors.muted, flex: 1, fontSize: 11, lineHeight: 17 }, spacer: { flex: 1, minHeight: 28 }, finish: { height: 58, borderRadius: 18, backgroundColor: colors.danger, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, finishText: { color: colors.text, fontSize: 16, fontWeight: '900' } });
