import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ActivityFlowShell } from '@/components/ActivityFlowShell';
import { ActivitySelector } from '@/components/ActivitySelector';
import { colors } from '@/theme';
import { useActiveActivity } from '@/features/activity/useActiveActivity';
import { useTarget } from '@/features/targets/useTarget';

export default function SelectActivityScreen() {
  const active=useActiveActivity();const{target}=useTarget();
  if(active)return <ActivityFlowShell eyebrow="SESSION ACTIVE" title="Activity in progress"><View style={styles.note}><Text style={styles.noteTitle}>{active.type.toUpperCase()}</Text><Text style={styles.noteCopy}>Only one activity can run at a time. Return to your existing session.</Text><Pressable style={styles.resume} onPress={()=>router.replace({pathname:'/activity/active',params:{type:active.type,sessionId:active.id}})}><Text style={styles.resumeText}>RESUME ACTIVITY</Text></Pressable></View></ActivityFlowShell>;
  return <ActivityFlowShell eyebrow="NEW SESSION" title="Choose activity"><View style={styles.hero}><Text style={styles.heroTitle}>How are you moving?</Text><Text style={styles.copy}>Choose an outdoor mode, start tracking, then put your phone away.</Text></View>{target?<View style={styles.target}><Text style={styles.noteTitle}>TARGET</Text><Text style={styles.targetName}>{target.territoryName}</Text><Text style={styles.noteCopy}>Normal activity progress is earned anywhere you move.</Text></View>:null}<ActivitySelector onSelect={(type) => { if(type !== 'indoor' || (__DEV__ && process.env.EXPO_PUBLIC_ENABLE_INDOOR_DEBUG === 'true')) router.replace({ pathname: '/activity/active', params: { type } }); }} /><View style={styles.note}><Ionicons name="shield-checkmark-outline" size={22} color={colors.cyan}/><View style={styles.noteBody}><Text style={styles.noteTitle}>PRIVATE OUTDOOR TRACKING</Text><Text style={styles.noteCopy}>Outdoor activities use precise GPS and can continue while your screen is locked where supported. Your route stays private by default.</Text></View></View></ActivityFlowShell>;
}
const styles = StyleSheet.create({target:{marginBottom:16,padding:14,borderRadius:14,borderWidth:1,borderColor:colors.cyan,backgroundColor:colors.surface},targetName:{color:colors.text,fontSize:16,fontWeight:'900',marginTop:4}, hero: { marginTop: 12, marginBottom: 24 }, heroTitle: { color: colors.text, fontSize: 30, lineHeight: 36, fontWeight: '900' }, copy: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 8 }, note: { flexDirection: 'row', gap: 12, marginTop: 22, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 15, backgroundColor: colors.surface }, noteBody: { flex: 1 }, noteTitle: { color: colors.cyan, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, noteCopy: { color: colors.muted, marginTop: 5, fontSize: 12, lineHeight: 18 },resume:{marginTop:18,padding:16,borderRadius:14,backgroundColor:colors.lime,alignItems:'center'},resumeText:{color:colors.background,fontWeight:'900'} });
