import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { rivalryRepository } from '@/services/backend/rivalryRepository';
import type { RivalryDetail, SharedTerritory } from '@/features/social/types';
import { colors } from '@/theme';

const when=(value:string)=>{const days=Math.floor((Date.now()-new Date(value).getTime())/86400000);return days<1?'TODAY':days===1?'YESTERDAY':`${days} DAYS AGO`};
export default function RivalryDetailScreen(){const{id}=useLocalSearchParams<{id:string}>();const[detail,setDetail]=useState<RivalryDetail|null>(null);const[territories,setTerritories]=useState<SharedTerritory[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);useFocusEffect(useCallback(()=>{let active=true;void Promise.all([rivalryRepository.getDetail(id),rivalryRepository.getSharedTerritories(id)]).then(([d,t])=>{if(active){setDetail(d);setTerritories(t)}}).catch(()=>{if(active)setError('This rivalry is unavailable.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id]));if(loading)return <View style={s.center}><ActivityIndicator color={colors.lime}/></View>;if(!detail)return <View style={s.center}><Text style={s.muted}>{error}</Text><Pressable onPress={()=>router.back()}><Text style={s.link}>GO BACK</Text></Pressable></View>;return <ScrollView contentContainerStyle={s.screen}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={25} color={colors.text}/></Pressable><Text style={s.title}>RIVALRY</Text></View><Pressable onPress={()=>router.push({pathname:'/player/[id]',params:{id}})} style={s.identity}><View><Text style={s.name}>{detail.displayName}</Text><Text style={s.handle}>@{detail.username}{detail.level!=null?` · LV. ${detail.level}`:''}</Text></View><Text style={s.relationship}>{detail.relationshipStatus==='friends'?'FRIEND + RIVAL':'RIVAL'}</Text></Pressable><Text style={s.section}>BATTLES · LAST 30 DAYS</Text><View style={s.grid}><Stat value={detail.myBattleWins} label="YOUR CAPTURES"/><Stat value={detail.theirBattleWins} label="THEIR CAPTURES"/><Stat value={detail.contestedBattles} label="CONTESTED"/><Stat value={detail.battlesLast30Days} label="TOTAL CLASHES"/></View><Text style={s.section}>SHARED TERRITORIES</Text><View style={s.grid}><Stat value={detail.sharedTerritories} label="SHARED"/><Stat value={detail.territoriesILead} label="YOU LEAD"/><Stat value={detail.territoriesTheyLead} label="THEY LEAD"/></View>{territories.map(t=><View key={t.territoryId} style={s.territory}><Text style={s.territoryName}>{t.territoryName}</Text><Text style={s.muted}>{t.myInfluence} YOU  ·  {t.theirInfluence} THEM  ·  {t.status.replaceAll('_',' ').toUpperCase()}</Text></View>)}<Text style={s.section}>RECENT CLASHES</Text>{detail.recentBattles.map(b=><View key={b.battleId} style={s.clash}><View><Text style={s.territoryName}>{b.territoryName}</Text><Text style={s.muted}>{b.result==='captured'?'TERRITORY CAPTURED':b.result==='contested'?'TERRITORY CONTESTED':'PRESSURE APPLIED'} · {b.role.toUpperCase()}</Text></View><Text style={s.date}>{when(b.createdAt)}</Text></View>)}</ScrollView>}
function Stat({value,label}:{value:number;label:string}){return <View style={s.stat}><Text style={s.value}>{value}</Text><Text style={s.label}>{label}</Text></View>}
const s=StyleSheet.create({screen:{flexGrow:1,backgroundColor:colors.background,padding:18,paddingTop:28},center:{flex:1,backgroundColor:colors.background,alignItems:'center',justifyContent:'center',gap:14},header:{flexDirection:'row',alignItems:'center',gap:12},title:{color:colors.text,fontSize:24,fontWeight:'900'},identity:{marginTop:22,padding:18,borderWidth:1,borderColor:colors.violet,borderRadius:16,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center'},name:{color:colors.text,fontSize:22,fontWeight:'900'},handle:{color:colors.cyan,marginTop:4},relationship:{marginLeft:'auto',color:colors.violet,fontSize:9,fontWeight:'900'},section:{color:colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.4,marginTop:24,marginBottom:9},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},stat:{backgroundColor:colors.surface,borderRadius:13,borderWidth:1,borderColor:colors.border,padding:13,minWidth:'31%',flexGrow:1},value:{color:colors.text,fontSize:20,fontWeight:'900'},label:{color:colors.muted,fontSize:8,fontWeight:'900',marginTop:4},territory:{padding:13,borderBottomWidth:1,borderColor:colors.border},territoryName:{color:colors.text,fontWeight:'800'},muted:{color:colors.muted,fontSize:10,marginTop:4},clash:{flexDirection:'row',justifyContent:'space-between',padding:14,backgroundColor:colors.surface,borderRadius:12,marginBottom:8},date:{color:colors.cyan,fontSize:9,fontWeight:'900'},link:{color:colors.lime,fontWeight:'900'}});
