import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { notificationRepository } from '@/services/backend/notificationRepository';
import type { SocialNotification } from '@/features/social/types';
import { colors } from '@/theme';

const icon=(type:SocialNotification['type'])=>type.startsWith('FRIEND')?'person-outline':type.includes('ACHIEVEMENT')||type.includes('OBJECTIVE')?'trophy-outline':type==='RIVALRY_STARTED'?'people-outline':'shield-outline';
const title=(n:SocialNotification)=>{const actor=n.actorDisplayName??n.actorUsername??'A player';const territory=n.territoryName??'a territory';switch(n.type){case'FRIEND_REQUEST':return`${actor} sent you a friend request.`;case'FRIEND_ACCEPTED':return`${actor} accepted your friend request.`;case'BATTLE_PRESSURE_RECEIVED':return`${actor} applied pressure to ${territory}.`;case'TERRITORY_CONTESTED':return`${territory} is now contested.`;case'TERRITORY_LOST':return`${actor} took the lead in ${territory}.`;case'RIVALRY_STARTED':return`${actor} is now one of your rivals.`;case'ACHIEVEMENT_UNLOCKED':return`Achievement unlocked: ${String(n.metadata.achievementKey??'New achievement').replaceAll('_',' ')}.`;case'OBJECTIVE_COMPLETED':return`Weekly objective complete: ${String(n.metadata.objectiveKey??'Objective').replaceAll('_',' ')}.`;}};
const ago=(value:string)=>{const seconds=Math.max(0,(Date.now()-new Date(value).getTime())/1000);if(seconds<3600)return`${Math.max(1,Math.floor(seconds/60))}m ago`;if(seconds<86400)return`${Math.floor(seconds/3600)}h ago`;return`${Math.floor(seconds/86400)}d ago`};
export default function Notifications(){const[items,setItems]=useState<SocialNotification[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{try{setItems(await notificationRepository.getNotifications());setError(null)}catch(e){setError(e instanceof Error?e.message:'Notifications are unavailable.')}finally{setLoading(false)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));const open=async(n:SocialNotification)=>{if(!n.readAt){await notificationRepository.markRead(n.id);setItems(current=>current.map(x=>x.id===n.id?{...x,readAt:new Date().toISOString()}:x))}if(n.type==='FRIEND_REQUEST')router.push('/friends?section=requests');else if(n.type==='RIVALRY_STARTED'&&n.actorUserId)router.push({pathname:'/rivalry/[id]',params:{id:n.actorUserId}});else if(n.type.includes('ACHIEVEMENT')||n.type.includes('OBJECTIVE'))router.push('/profile');else if(n.territoryId)router.push('/map')};const markAll=async()=>{await notificationRepository.markAllRead();const now=new Date().toISOString();setItems(current=>current.map(x=>({...x,readAt:x.readAt??now})))};return <View style={s.screen}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={25} color={colors.text}/></Pressable><Text style={s.title}>NOTIFICATIONS</Text><Pressable onPress={()=>void markAll()}><Text style={s.all}>MARK ALL READ</Text></Pressable></View>{loading?<ActivityIndicator color={colors.lime} style={s.loading}/>:<ScrollView contentContainerStyle={s.list}>{error?<Text style={s.error}>{error}</Text>:null}{items.map(n=><Pressable key={n.id} onPress={()=>void open(n)} style={[s.item,!n.readAt&&s.unread]}><View style={s.icon}><Ionicons name={icon(n.type)} size={20} color={colors.cyan}/></View><View style={s.copy}><Text style={s.message}>{title(n)}</Text><Text style={s.time}>{ago(n.createdAt)}</Text></View>{!n.readAt?<View style={s.dot}/>:null}</Pressable>)}{!error&&items.length===0?<Text style={s.empty}>NO NOTIFICATIONS YET</Text>:null}</ScrollView>}</View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background,paddingTop:24},header:{flexDirection:'row',alignItems:'center',gap:14,padding:16,borderBottomWidth:1,borderColor:colors.border},title:{color:colors.text,fontSize:20,fontWeight:'900',flex:1},all:{color:colors.lime,fontSize:9,fontWeight:'900'},loading:{marginTop:60},list:{padding:16,gap:9},item:{flexDirection:'row',alignItems:'center',padding:14,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,gap:12},unread:{borderColor:colors.cyan,backgroundColor:colors.surfaceRaised},icon:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},copy:{flex:1},message:{color:colors.text,lineHeight:19},time:{color:colors.muted,fontSize:10,marginTop:4},dot:{width:8,height:8,borderRadius:4,backgroundColor:colors.danger},empty:{color:colors.muted,textAlign:'center',marginTop:40,fontWeight:'900'},error:{color:colors.danger,textAlign:'center'}});
