import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { PlayerHeader } from '@/components/PlayerHeader';
import { colors } from '@/theme';
import type { TabScreenData } from '@/types/game';

export function PlaceholderScreen({ data }: { data: TabScreenData }) {
  return <View style={styles.screen}><PlayerHeader /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><LinearGradient colors={[`${data.accent}22`, colors.surface]} style={[styles.hero, { borderColor: `${data.accent}55` }]}><View style={[styles.heroIcon, { backgroundColor: `${data.accent}22` }]}><Ionicons name={data.icon} size={32} color={data.accent} /></View><Text style={[styles.eyebrow, { color: data.accent }]}>{data.eyebrow}</Text><Text style={styles.title}>{data.title}</Text><Text style={styles.description}>{data.description}</Text></LinearGradient><View style={styles.stats}>{data.stats.map((stat) => <View key={stat.label} style={styles.stat}><Text style={styles.statLabel}>{stat.label}</Text><Text style={styles.statValue}>{stat.value}</Text></View>)}</View><Text style={styles.sectionTitle}>OVERVIEW</Text>{data.items.map((item) => <View key={item.title} style={styles.row}><View style={[styles.rowIcon, { backgroundColor: `${data.accent}18` }]}><Ionicons name={item.icon} size={20} color={data.accent} /></View><View><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowDetail}>{item.detail}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} style={styles.chevron} /></View>)}</ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: 16, paddingBottom: 28, gap: 12 }, hero: { alignItems: 'center', padding: 26, borderRadius: 26, borderWidth: 1 }, heroIcon: { width: 62, height: 62, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, eyebrow: { fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.text, fontSize: 30, fontWeight: '900', letterSpacing: -0.6, marginTop: 3 }, description: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 8, maxWidth: 300 }, stats: { flexDirection: 'row', gap: 10 }, stat: { flex: 1, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 14 }, statLabel: { color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1 }, statValue: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 4 }, sectionTitle: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.3, marginTop: 8 }, row: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 12 }, rowIcon: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, rowTitle: { color: colors.text, fontSize: 14, fontWeight: '800' }, rowDetail: { color: colors.muted, fontSize: 11, marginTop: 3 }, chevron: { marginLeft: 'auto' } });
