import { LinearGradient } from 'expo-linear-gradient';
import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { WEEKLY_DISTANCE_GOAL_KM } from '@/config/game';
import { useAuth } from '@/features/auth/AuthContext';
import { weeklySummaryRepository, type WeeklySummary } from '@/services/backend/weeklySummaryRepository';
import { activityRepository } from '@/services/storage/activityRepository';
import { colors } from '@/theme';
export function WeeklyProgress(){const{user}=useAuth();const[summary,setSummary]=useState<WeeklySummary|null>();const[pending,setPending]=useState(0);useEffect(()=>{let active=true;void weeklySummaryRepository.get().then(v=>{if(active)setSummary(v)});if(user)void activityRepository.pending(user.id).then(items=>{if(active)setPending(items.reduce((n,x)=>n+x.distanceMeters,0))});return()=>{active=false}},[user]);if(summary===undefined)return <View style={styles.card}><Text style={styles.label}>WEEKLY PROGRESS · LOADING</Text></View>;const km=(summary?.outdoor_distance_meters??0)/1000;const percent=Math.min(100,km/WEEKLY_DISTANCE_GOAL_KM*100);return <View style={styles.card}><View style={styles.header}><View><Text style={styles.label}>WEEKLY DISTANCE {summary?.source==='cache'?'· LAST KNOWN':''}</Text><Text style={styles.value}>{km.toFixed(1)} <Text style={styles.total}>/ {WEEKLY_DISTANCE_GOAL_KM} km</Text></Text></View><Text style={styles.activities}>{summary?.activity_count??0} ACTIVITIES</Text></View><View style={styles.bar}><LinearGradient colors={[colors.lime,colors.cyan]} style={[styles.fill,{width:`${percent}%`}]}/></View>{pending>0?<Text style={styles.pending}>+ {(pending/1000).toFixed(1)} km pending sync</Text>:null}</View>}
const styles=StyleSheet.create({card:{minHeight:58,padding:12,borderRadius:17,borderWidth:1,borderColor:colors.border,backgroundColor:'#0C1614'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},label:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1},value:{color:colors.text,fontSize:17,fontWeight:'900',marginTop:2},total:{color:colors.muted,fontSize:10},activities:{color:colors.cyan,fontSize:8,fontWeight:'900'},bar:{height:5,borderRadius:3,backgroundColor:colors.border,overflow:'hidden',marginTop:6},fill:{height:'100%'},pending:{color:colors.gold,fontSize:8,fontWeight:'800',marginTop:5}});
