import { LinearGradient } from 'expo-linear-gradient';
import { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { WEEKLY_DISTANCE_GOAL_KM } from '@/config/game';
import { useAuth } from '@/features/auth/AuthContext';
import { weeklySummaryRepository, type WeeklySummary } from '@/services/backend/weeklySummaryRepository';
import { activityRepository } from '@/services/storage/activityRepository';
import { colors } from '@/theme';
export function WeeklyProgress(){const{user}=useAuth();const[expanded,setExpanded]=useState(false);const[summary,setSummary]=useState<WeeklySummary|null|undefined>(()=>weeklySummaryRepository.getLatest());const[pending,setPending]=useState(0);const pendingRequest=useRef(0);useEffect(()=>{let active=true;const unsubscribe=weeklySummaryRepository.subscribe(value=>{if(active)setSummary(value)});void weeklySummaryRepository.refresh();return()=>{active=false;unsubscribe()}},[user]);useEffect(()=>{let active=true;const loadPending=()=>{const request=++pendingRequest.current;if(!user){setPending(0);return;}void activityRepository.pending(user.id).then(items=>{if(active&&request===pendingRequest.current)setPending(items.reduce((n,x)=>n+x.distanceMeters,0))})};loadPending();const unsubscribe=activityRepository.subscribe(loadPending);return()=>{active=false;unsubscribe()}},[user]);const km=(summary?.outdoor_distance_meters??0)/1000;const percent=Math.min(100,km/WEEKLY_DISTANCE_GOAL_KM*100);return <Pressable accessibilityLabel={`Weekly distance ${summary===undefined?'loading':`${km.toFixed(1)} of ${WEEKLY_DISTANCE_GOAL_KM} kilometers`}. Tap to ${expanded?'collapse':'expand'}.`} accessibilityRole="button" onPress={()=>setExpanded(value=>!value)} style={[styles.card,expanded&&styles.expanded]}><View style={styles.compactRow}><Text style={styles.label}>WEEKLY</Text><Text style={styles.compactValue}>{summary===undefined?'…':`${km.toFixed(1)}/${WEEKLY_DISTANCE_GOAL_KM} KM`}</Text></View><View style={styles.bar}><LinearGradient colors={[colors.lime,colors.cyan]} style={[styles.fill,{width:`${percent}%`}]}/></View>{expanded?<View style={styles.details}><Text style={styles.value}>{km.toFixed(1)} <Text style={styles.total}>/ {WEEKLY_DISTANCE_GOAL_KM} km</Text></Text><Text style={styles.activities}>{summary?.activity_count??0} ACTIVITIES{summary?.source==='cache'?' · LAST KNOWN':''}</Text>{pending>0?<Text style={styles.pending}>+ {(pending/1000).toFixed(1)} km pending sync</Text>:null}</View>:null}</Pressable>}
const styles=StyleSheet.create({card:{alignSelf:'flex-start',minWidth:132,paddingHorizontal:11,paddingVertical:9,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.mapOverlay},expanded:{width:'100%',padding:12},compactRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:9},details:{marginTop:7},label:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1},compactValue:{color:colors.text,fontSize:9,fontWeight:'900'},value:{color:colors.text,fontSize:17,fontWeight:'900'},total:{color:colors.muted,fontSize:10},activities:{color:colors.cyan,fontSize:8,fontWeight:'900',marginTop:2},bar:{height:3,borderRadius:3,backgroundColor:colors.border,overflow:'hidden',marginTop:6},fill:{height:'100%'},pending:{color:colors.gold,fontSize:8,fontWeight:'800',marginTop:5}});
