import { router, useFocusEffect } from 'expo-router';
import { useCallback } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { PlayerHeader } from '@/components/PlayerHeader';
import { formatDuration } from '@/features/activity/activityRules';
import { useActivityHistory } from '@/features/activity/useActivityHistory';
import type { ActivityHistoryItem } from '@/features/activity/activityHistory';
import { useAuth } from '@/features/auth/AuthContext';
import { colors } from '@/theme';
export default function ActivitiesScreen(){const{user}=useAuth();const{items,loading,loadingMore,serverFailed,hasMore,refresh,loadMore}=useActivityHistory(user?.id);useFocusEffect(useCallback(()=>{void refresh();return undefined},[refresh]));const empty=loading?<ActivityIndicator color={colors.lime} style={styles.loader}/>:serverFailed?<View style={styles.card}><Text style={styles.cardTitle}>COULDN&apos;T LOAD ACTIVITY HISTORY</Text><Text style={styles.copy}>Your synchronized activities are still safe.</Text><Pressable onPress={()=>void refresh()}><Text style={styles.retry}>TRY AGAIN</Text></Pressable></View>:<View style={styles.card}><Text style={styles.cardTitle}>NO OUTDOOR ACTIVITIES YET</Text><Text style={styles.copy}>Finish a GPS-tracked walk, run or ride to see it here.</Text></View>;return <View style={styles.screen}><PlayerHeader/><FlatList data={items} keyExtractor={item=>`${item.source}:${item.activityId??item.clientActivityId}`} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void refresh()} tintColor={colors.lime}/>} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.eyebrow}>ACTIVITY LOG</Text><Text style={styles.title}>Your activities</Text></>} ListEmptyComponent={empty} renderItem={({item})=><ActivityCard item={item} retry={refresh}/>} ItemSeparatorComponent={()=> <View style={styles.separator}/>} ListFooterComponent={hasMore?<Pressable disabled={loadingMore} onPress={()=>void loadMore()} style={styles.more}><Text style={styles.moreText}>{loadingMore?'LOADING…':'SHOW 10 MORE'}</Text></Pressable>:null}/></View>}
function ActivityCard({item,retry}:{item:ActivityHistoryItem;retry:()=>Promise<void>}){const reference=item.localActivityId??item.activityId;return <Pressable accessibilityRole="button" onPress={()=>reference&&router.push({pathname:'/activity/results',params:{activityId:reference,serverActivityId:item.activityId,type:item.type}})} style={styles.card}><View style={styles.row}><Text style={styles.type}>{item.type.toUpperCase()}</Text><Text style={[styles.sync,item.syncStatus==='synced'&&styles.synced]}>{item.syncStatus==='synced'?'SERVER CONFIRMED':item.syncStatus.toUpperCase()}</Text></View><Text style={styles.distance}>{(item.distanceMeters/1000).toFixed(2)} km</Text><Text style={styles.copy}>{new Date(item.endedAt).toLocaleDateString()} · {formatDuration(item.durationSeconds)} · {item.territoryCount} territories</Text>{item.syncStatus==='pending'||item.syncStatus==='failed'?<><Text style={styles.error}>Saved safely on this device. Server sync will retry.</Text><Pressable onPress={event=>{event.stopPropagation();void retry()}}><Text style={styles.retry}>RETRY SYNC</Text></Pressable></>:null}</Pressable>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:16,paddingBottom:36},eyebrow:{color:colors.cyan,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:8},title:{color:colors.text,fontSize:29,fontWeight:'900',marginBottom:12},separator:{height:12},loader:{margin:40},card:{backgroundColor:colors.surface,padding:18,borderRadius:19,borderWidth:1,borderColor:colors.border},row:{flexDirection:'row',justifyContent:'space-between'},cardTitle:{color:colors.text,fontWeight:'900',fontSize:17},copy:{color:colors.muted,marginTop:5,fontSize:11,lineHeight:17},type:{color:colors.cyan,fontWeight:'900',fontSize:9},sync:{color:colors.gold,fontWeight:'900',fontSize:8},synced:{color:colors.lime},distance:{color:colors.text,fontWeight:'900',fontSize:23,marginTop:4},error:{color:colors.gold,fontSize:10,marginTop:8},retry:{color:colors.cyan,fontSize:10,fontWeight:'900',marginTop:10},more:{minHeight:50,marginTop:16,borderRadius:14,borderWidth:1,borderColor:colors.cyan,alignItems:'center',justifyContent:'center'},moreText:{color:colors.cyan,fontWeight:'900',fontSize:11}});
