import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { PlayerHeader } from '@/components/PlayerHeader';
import { formatDuration } from '@/features/activity/activityRules';
import { useAuth } from '@/features/auth/AuthContext';
import { activitySyncService } from '@/services/backend/activitySyncService';
import { activityRepository, type StoredOutdoorActivity } from '@/services/storage/activityRepository';
import { colors } from '@/theme';
export default function ActivitiesScreen(){const{user}=useAuth();const[items,setItems]=useState<StoredOutdoorActivity[]>([]);const load=useCallback(()=>{void activityRepository.list(user?.id).then(setItems)},[user?.id]);useFocusEffect(useCallback(()=>{load();return activityRepository.subscribe(load)},[load]));const retry=async()=>{if(!user)return;await activitySyncService.syncPending(user.id,true);load()};return <View style={styles.screen}><PlayerHeader/><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ACTIVITY LOG</Text><Text style={styles.title}>Your conquests</Text>{items.length===0?<View style={styles.card}><Text style={styles.cardTitle}>No outdoor activities yet</Text><Text style={styles.copy}>Finish a GPS-tracked walk, run or ride to see it here.</Text></View>:items.map(item=><View key={item.id} style={styles.card}><View style={styles.row}><Text style={styles.type}>{item.type.toUpperCase()}</Text><Text style={[styles.sync,item.syncStatus==='synced'&&styles.synced]}>{item.syncStatus.toUpperCase()}</Text></View><Text style={styles.distance}>{(item.distanceMeters/1000).toFixed(2)} km</Text><Text style={styles.copy}>{formatDuration(item.durationSeconds)} · {item.traversals.length} territories · local result</Text>{item.syncStatus==='failed'?<><Text style={styles.error}>Saved safely on this device. Server sync will retry.</Text><Pressable onPress={()=>void retry()}><Text style={styles.retry}>RETRY SYNC</Text></Pressable></>:null}</View>)}</ScrollView></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:16,gap:12},eyebrow:{color:colors.cyan,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:8},title:{color:colors.text,fontSize:29,fontWeight:'900'},card:{backgroundColor:colors.surface,padding:18,borderRadius:19,borderWidth:1,borderColor:colors.border},row:{flexDirection:'row',justifyContent:'space-between'},cardTitle:{color:colors.text,fontWeight:'900',fontSize:17},copy:{color:colors.muted,marginTop:5,fontSize:11},type:{color:colors.cyan,fontWeight:'900',fontSize:9,letterSpacing:1},sync:{color:colors.gold,fontWeight:'900',fontSize:8},synced:{color:colors.lime},distance:{color:colors.text,fontWeight:'900',fontSize:23,marginTop:4},error:{color:colors.gold,fontSize:10,marginTop:8},retry:{color:colors.cyan,fontSize:10,fontWeight:'900',marginTop:10}});
