import { router, useFocusEffect } from 'expo-router';
import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { PlayerHeader } from '@/components/PlayerHeader';
import { formatDuration } from '@/features/activity/activityRules';
import { useAuth } from '@/features/auth/AuthContext';
import { activitySyncService } from '@/services/backend/activitySyncService';
import { ACTIVITY_PAGE_SIZE, activityRepository, type ActivityCursor, type StoredOutdoorActivity } from '@/services/storage/activityRepository';
import { colors } from '@/theme';

const dedupeActivities=(current:StoredOutdoorActivity[],next:StoredOutdoorActivity[])=>Array.from(new Map([...current,...next].map(item=>[item.clientActivityId,item])).values());
export default function ActivitiesScreen(){
 const{user}=useAuth();const[items,setItems]=useState<StoredOutdoorActivity[]>([]);const[cursor,setCursor]=useState<ActivityCursor|null>(null);const[loading,setLoading]=useState(true);const[loadingMore,setLoadingMore]=useState(false);const[pageError,setPageError]=useState<string|null>(null);const requestRef=useRef(false);
 const loadFirst=useCallback(async()=>{if(!user?.id||requestRef.current)return;requestRef.current=true;setLoading(true);try{const page=await activityRepository.listPage(user.id);setItems(page.items);setCursor(page.nextCursor);setPageError(null)}catch{setPageError('Could not refresh activities. Try again.')}finally{requestRef.current=false;setLoading(false)}},[user?.id]);
 const loadMore=useCallback(async()=>{if(!user?.id||!cursor||requestRef.current)return;requestRef.current=true;setLoadingMore(true);try{const page=await activityRepository.listPage(user.id,cursor);setItems(current=>dedupeActivities(current,page.items));setCursor(page.nextCursor);setPageError(null)}catch{setPageError('Could not load more activities. Try again.')}finally{requestRef.current=false;setLoadingMore(false)}},[cursor,user?.id]);
 useFocusEffect(useCallback(()=>{void loadFirst();return activityRepository.subscribe(()=>void loadFirst())},[loadFirst]));
 const retry=async()=>{if(!user)return;await activitySyncService.syncPending(user.id,true);await loadFirst()};
 return <View style={styles.screen}><PlayerHeader/><FlatList data={items} keyExtractor={item=>item.clientActivityId} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.eyebrow}>ACTIVITY LOG</Text><Text style={styles.title}>Your activities</Text></>} ListEmptyComponent={loading?<ActivityIndicator color={colors.lime} style={styles.loader}/>:<View style={styles.card}><Text style={styles.cardTitle}>No outdoor activities yet</Text><Text style={styles.copy}>Finish a GPS-tracked walk, run or ride to see it here.</Text></View>} renderItem={({item})=><ActivityCard item={item} retry={retry}/>} ItemSeparatorComponent={()=> <View style={styles.separator}/>} ListFooterComponent={cursor?<View style={styles.moreWrap}>{pageError?<Text style={styles.pageError}>{pageError}</Text>:null}<Pressable accessibilityRole="button" accessibilityLabel={`Show ${ACTIVITY_PAGE_SIZE} more activities`} disabled={loadingMore} onPress={()=>void loadMore()} style={({pressed})=>[styles.more,pressed&&styles.pressed,loadingMore&&styles.disabled]}><Text style={styles.moreText}>{loadingMore?'LOADING…':`SHOW ${ACTIVITY_PAGE_SIZE} MORE`}</Text></Pressable></View>:null}/></View>
}
function ActivityCard({item,retry}:{item:StoredOutdoorActivity;retry:()=>Promise<void>}){return <Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/activity/results',params:{activityId:item.id,type:item.type}})} style={styles.card}><View style={styles.row}><Text style={styles.type}>{item.type.toUpperCase()}</Text><Text style={[styles.sync,item.syncStatus==='synced'&&styles.synced]}>{item.syncStatus.toUpperCase()}</Text></View><Text style={styles.distance}>{((item.authoritativeDistanceMeters??item.distanceMeters)/1000).toFixed(2)} km</Text><Text style={styles.copy}>{new Date(item.endedAt).toLocaleDateString()} · {formatDuration(item.durationSeconds)} · {item.traversals.length} territories · {item.syncStatus==='synced'?'server confirmed':'estimated'}</Text>{item.syncStatus==='pending'||item.syncStatus==='failed'?<><Text style={styles.error}>Saved safely on this device. Server sync will retry.</Text><Pressable accessibilityRole="button" accessibilityLabel="Retry activity sync" onPress={event=>{event.stopPropagation();void retry()}}><Text style={styles.retry}>RETRY SYNC</Text></Pressable></>:null}</Pressable>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:16,paddingBottom:36},eyebrow:{color:colors.cyan,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:8},title:{color:colors.text,fontSize:29,fontWeight:'900',marginBottom:12},separator:{height:12},loader:{margin:40},card:{backgroundColor:colors.surface,padding:18,borderRadius:19,borderWidth:1,borderColor:colors.border},row:{flexDirection:'row',justifyContent:'space-between'},cardTitle:{color:colors.text,fontWeight:'900',fontSize:17},copy:{color:colors.muted,marginTop:5,fontSize:11,lineHeight:17},type:{color:colors.cyan,fontWeight:'900',fontSize:9,letterSpacing:1},sync:{color:colors.gold,fontWeight:'900',fontSize:8},synced:{color:colors.lime},distance:{color:colors.text,fontWeight:'900',fontSize:23,marginTop:4},error:{color:colors.gold,fontSize:10,marginTop:8},retry:{color:colors.cyan,fontSize:10,fontWeight:'900',marginTop:10},moreWrap:{marginTop:16},more:{minHeight:50,borderRadius:14,borderWidth:1,borderColor:colors.cyan,alignItems:'center',justifyContent:'center'},moreText:{color:colors.cyan,fontWeight:'900',fontSize:11,letterSpacing:1},pageError:{color:colors.danger,textAlign:'center',fontSize:11,marginBottom:9},pressed:{opacity:.75},disabled:{opacity:.55}});
