import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { PlayerHeader } from '@/components/PlayerHeader';
import { BattleHistory } from '@/components/profile/BattleHistory';
import { useAuth } from '@/features/auth/AuthContext';
import { BATTLE_COOLDOWN_HOURS, BATTLE_ENERGY_COST, BATTLE_INFLUENCE_REWARD, BATTLE_RECENT_ACTIVITY_DAYS, CAPTURE_PROTECTION_HOURS } from '@/features/battles/battleRules';
import { colors } from '@/theme';
export default function BattlesScreen(){const{progress}=useAuth();const[showRules,setShowRules]=useState(false);return <View style={styles.screen}><PlayerHeader/><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>TERRITORY PRESSURE</Text><Text style={styles.title}>BATTLES</Text><View style={styles.resource}><View><Text style={styles.resourceLabel}>CURRENT PLAYER RESOURCE</Text><Text style={styles.energy}>{progress?.energy??'—'} <Text style={styles.energyUnit}>ENERGY</Text></Text></View><Ionicons name="flash" size={26} color={colors.gold}/></View><Pressable accessibilityRole="button" accessibilityLabel="Find a rival territory on the map" onPress={()=>router.push('/map')} style={({pressed})=>[styles.mapButton,pressed&&styles.pressed]}><Ionicons name="map" size={19} color={colors.background}/><View><Text style={styles.actionOverline}>FIND A BATTLE</Text><Text style={styles.mapButtonText}>FIND A RIVAL TERRITORY</Text></View></Pressable><View><Text style={styles.ruleLabel}>BATTLE RULES</Text><View style={styles.stats}><Stat value={`-${BATTLE_ENERGY_COST}`} label="ENERGY COST"/><Stat value={`+${BATTLE_INFLUENCE_REWARD}`} label="INFLUENCE"/><Stat value={`${BATTLE_COOLDOWN_HOURS}H`} label="COOLDOWN"/><Stat value={`${CAPTURE_PROTECTION_HOURS}H`} label="PROTECTION"/></View></View><BattleHistory embedded limit={10}/><Pressable accessibilityRole="button" accessibilityState={{expanded:showRules}} onPress={()=>setShowRules(value=>!value)} style={styles.rulesToggle}><Text style={styles.sectionTitle}>HOW IT WORKS</Text><Ionicons name={showRules?'chevron-up':'chevron-down'} color={colors.cyan} size={18}/></Pressable>{showRules?<View style={styles.rules}><Rule icon="footsteps-outline" text={`Earn activity influence in a rival zone within the last ${BATTLE_RECENT_ACTIVITY_DAYS} days.`}/><Rule icon="analytics-outline" text="Build at least 25% of the rival leader's influence in that territory."/><Rule icon="shield-checkmark-outline" text={`Captures receive ${CAPTURE_PROTECTION_HOURS} hours of Battle Protection. Activities always remain active.`}/></View>:null}</ScrollView></View>}
function Stat({value,label}:{value:string;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>};function Rule({icon,text}:{icon:React.ComponentProps<typeof Ionicons>['name'];text:string}){return <View style={styles.rule}><Ionicons name={icon} size={19} color={colors.lime}/><Text style={styles.ruleText}>{text}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:14,paddingBottom:30,gap:12},eyebrow:{color:colors.gold,fontSize:9,fontWeight:'900',letterSpacing:1.5,marginTop:5},title:{color:colors.text,fontSize:30,fontWeight:'900'},resource:{padding:16,borderRadius:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},resourceLabel:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.2},energy:{color:colors.text,fontSize:23,fontWeight:'900',marginTop:3},energyUnit:{fontSize:10,color:colors.gold},mapButton:{minHeight:62,borderRadius:16,backgroundColor:colors.lime,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:11},actionOverline:{color:'#203126',fontWeight:'900',fontSize:7,letterSpacing:1.2},mapButtonText:{color:colors.background,fontWeight:'900',fontSize:12,letterSpacing:.6,marginTop:2},ruleLabel:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.2,marginBottom:7},stats:{flexDirection:'row',flexWrap:'wrap',gap:7},stat:{flexGrow:1,minWidth:'46%',alignItems:'center',padding:11,borderRadius:14,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},statValue:{color:colors.text,fontSize:17,fontWeight:'900'},statLabel:{color:colors.muted,fontSize:7,fontWeight:'900',letterSpacing:.8,marginTop:3},rulesToggle:{minHeight:48,paddingHorizontal:15,borderRadius:15,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},sectionTitle:{color:colors.cyan,fontSize:10,fontWeight:'900',letterSpacing:1.4},rules:{padding:16,borderRadius:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:13},rule:{flexDirection:'row',alignItems:'center',gap:11},ruleText:{flex:1,color:colors.muted,fontSize:11,lineHeight:16},pressed:{opacity:.78}});
