import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { Avatar } from '@/components/profile/Avatar';
import { BattleHistory } from '@/components/profile/BattleHistory';
import { ProfileTabs } from '@/components/profile/ProfileTabs';
import { ProfileAchievements, ProfileActivities, ProfileTerritories } from '@/components/profile/ProfileSections';
import { useAuth } from '@/features/auth/AuthContext';
import type { PublicPlayerProfile } from '@/features/auth/types';
import type { ExplorationSummary } from '@/features/exploration/explorationRules';
import { resolveProfileTab, type ProfileTab } from '@/features/profile/profileTabs';
import { profileRepository } from '@/services/backend/profileRepository';
import { explorationRepository } from '@/services/backend/explorationRepository';
import { friendshipRepository, type SocialCounts } from '@/services/backend/friendshipRepository';
import { activeActivityRepository } from '@/services/storage/activeActivityRepository';
import { activityRepository, type StoredOutdoorActivity } from '@/services/storage/activityRepository';
import { colors } from '@/theme';

const Stat=({label,value}:{label:string;value:string})=><View style={s.stat}><Text numberOfLines={1} style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>;
export default function ProfileScreen(){
 const params=useLocalSearchParams<{tab?:string|string[]}>();const{profile,progress,signOut}=useAuth();
 const[selected,setSelected]=useState<ProfileTab>(()=>resolveProfileTab(params.tab));const[stats,setStats]=useState<PublicPlayerProfile|null>(null);const[social,setSocial]=useState<SocialCounts>({friends_count:0,pending_request_count:0});const[summary,setSummary]=useState<ExplorationSummary|null|undefined>(()=>explorationRepository.getLatest());const[activities,setActivities]=useState<StoredOutdoorActivity[]>([]);const[loadingActivities,setLoadingActivities]=useState(true);
 useEffect(()=>setSelected(resolveProfileTab(params.tab)),[params.tab]);
 const refresh=useCallback(()=>{if(!profile?.id)return;void profileRepository.getPublic(profile.id).then(setStats).catch(()=>setStats(null));void friendshipRepository.getCounts().then(setSocial).catch(()=>setSocial({friends_count:0,pending_request_count:0}));setLoadingActivities(true);void activityRepository.list(profile.id).then(setActivities).finally(()=>setLoadingActivities(false));void explorationRepository.refresh()},[profile?.id]);
 useFocusEffect(useCallback(()=>{refresh();return activityRepository.subscribe(refresh)},[refresh]));useEffect(()=>explorationRepository.subscribe(setSummary),[]);
 const select=(tab:ProfileTab)=>{setSelected(tab);router.setParams({tab:tab==='overview'?undefined:tab})};
 const leave=async()=>{const active=await activeActivityRepository.get();if(active){Alert.alert('Activity in progress','Finish or discard the current activity before signing out.');return;}const result=await signOut();if(!result.ok)Alert.alert('Sign out failed',result.message)};
 if(!profile)return null;const xp=progress?.xp;
 return <ScrollView contentContainerStyle={s.screen}><LinearGradient colors={['#173027',colors.background]} style={s.hero}><View style={s.avatarRing}><Avatar name={profile.display_name} url={profile.avatar_url} size={100}/></View><Text numberOfLines={1} style={s.name}>{profile.display_name}</Text><Text numberOfLines={1} style={s.username}>@{profile.username}</Text><Text style={s.level}>LEVEL {progress?.level??'—'}</Text><Text style={s.xpLabel}>{xp==null?'XP unavailable':`${xp%1000} / 1000 XP`}</Text>{profile.bio?<Text style={s.bio}>{profile.bio}</Text>:null}<View style={s.chips}>{profile.preferred_activities.map(a=><Text key={a} style={s.chip}>{a.toUpperCase()}</Text>)}</View>{profile.city||profile.region?<Text style={s.location}>⌖ {[profile.city,profile.region].filter(Boolean).join(' · ')}</Text>:null}</LinearGradient><ProfileTabs selected={selected} onSelect={select}/>{selected==='overview'?<Overview stats={stats} social={social} summary={summary}/>:selected==='activities'?<ProfileActivities items={activities} loading={loadingActivities}/>:selected==='territories'?<ProfileTerritories summary={summary} loading={summary===undefined}/>:<ProfileAchievements summary={summary} loading={summary===undefined}/>}<Pressable accessibilityLabel="Sign out" onPress={()=>void leave()}><Text style={s.signout}>SIGN OUT</Text></Pressable></ScrollView>
}
function Overview({stats,social,summary}:{stats:PublicPlayerProfile|null;social:SocialCounts;summary:ExplorationSummary|null|undefined}){return <View><View style={s.stats}><Stat label="TOTAL DISTANCE" value={stats?.total_distance==null?'—':`${(stats.total_distance/1000).toFixed(1)} km`}/><Stat label="ACTIVITIES" value={stats?.total_activities==null?'—':String(stats.total_activities)}/><Stat label="TERRITORIES" value={stats?.territories_count==null?'—':String(stats.territories_count)}/><Stat label="TOTAL INFLUENCE" value={stats?.total_influence==null?'—':String(stats.total_influence)}/></View><View style={s.snapshot}><Text style={s.sectionTitle}>EXPLORATION SNAPSHOT</Text><Text style={s.snapshotValue}>{summary?`${summary.zonesControlled} controlled · ${summary.newZonesThisWeek} new this week`:'Exploration data is unavailable.'}</Text>{summary?.objectives.slice(0,3).map(o=><Text key={o.key} style={s.objective}>{o.title.toUpperCase()}  {Math.min(o.progress,o.target)} / {o.target}{o.rewardedAt?'  ✓':''}</Text>)}</View><BattleHistory/><Pressable accessibilityLabel={`Social, ${social.friends_count} friends, ${social.pending_request_count} requests`} onPress={()=>router.push('/friends')} style={s.social}><View><Text style={s.socialTitle}>SOCIAL</Text><Text style={s.socialCount}>{social.friends_count} FRIENDS · {social.pending_request_count} REQUESTS</Text></View>{social.pending_request_count>0?<View style={s.badge}><Text style={s.badgeText}>{social.pending_request_count}</Text></View>:null}<Text style={s.arrow}>›</Text></Pressable><View style={s.actions}><Pressable accessibilityLabel="Edit profile" onPress={()=>router.push('/profile/edit')} style={s.primary}><Text style={s.primaryText}>EDIT PROFILE</Text></Pressable><Pressable accessibilityLabel="Privacy settings" onPress={()=>router.push('/profile/privacy')} style={s.secondary}><Text style={s.secondaryText}>PRIVACY</Text></Pressable></View></View>}
const s=StyleSheet.create({screen:{paddingBottom:30,backgroundColor:colors.background},hero:{alignItems:'center',paddingHorizontal:20,paddingTop:22,paddingBottom:19,borderBottomWidth:1,borderColor:colors.border},avatarRing:{padding:4,borderWidth:3,borderColor:colors.lime,borderRadius:58,shadowColor:colors.lime,shadowOpacity:.2,shadowRadius:8},name:{fontSize:27,color:colors.text,fontWeight:'900',marginTop:11,maxWidth:'100%'},username:{color:colors.cyan,marginTop:2,maxWidth:'100%'},level:{color:colors.gold,fontWeight:'900',fontSize:10,letterSpacing:1.2,marginTop:9},xpLabel:{color:colors.muted,fontSize:9,marginTop:4,fontWeight:'800'},bio:{color:colors.text,textAlign:'center',lineHeight:19,marginTop:12,maxWidth:330},chips:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:7,marginTop:12},chip:{color:colors.lime,fontSize:9,fontWeight:'900',borderWidth:1,borderColor:'#52663A',padding:7,borderRadius:12},location:{color:colors.muted,marginTop:12},stats:{flexDirection:'row',flexWrap:'wrap',gap:8,padding:14},stat:{width:'48%',flexGrow:1,minWidth:130,height:76,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,padding:13},statValue:{color:colors.text,fontSize:20,fontWeight:'900'},statLabel:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1,marginTop:5},snapshot:{marginHorizontal:14,marginBottom:14,padding:16,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},sectionTitle:{color:colors.cyan,fontSize:10,fontWeight:'900',letterSpacing:1.3},snapshotValue:{color:colors.text,fontWeight:'800',marginTop:8},objective:{color:colors.muted,fontSize:9,fontWeight:'800',marginTop:8},social:{marginHorizontal:14,marginBottom:12,padding:16,flexDirection:'row',alignItems:'center',borderRadius:15,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.cyan},socialTitle:{color:colors.cyan,fontWeight:'900',letterSpacing:1.5},socialCount:{color:colors.muted,fontSize:9,fontWeight:'800',marginTop:4},badge:{marginLeft:'auto',backgroundColor:colors.danger,minWidth:24,height:24,borderRadius:12,alignItems:'center',justifyContent:'center'},badgeText:{color:colors.text,fontSize:10,fontWeight:'900'},arrow:{color:colors.cyan,fontSize:28,marginLeft:10},actions:{flexDirection:'row',gap:8,paddingHorizontal:14},primary:{flex:2,backgroundColor:colors.lime,borderRadius:13,alignItems:'center',padding:14},primaryText:{color:colors.background,fontWeight:'900'},secondary:{flex:1,borderWidth:1,borderColor:colors.cyan,borderRadius:13,alignItems:'center',padding:14},secondaryText:{color:colors.cyan,fontWeight:'900'},signout:{textAlign:'center',color:colors.danger,fontWeight:'900',padding:20}});
