import { Ionicons } from '@expo/vector-icons';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Animated, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import type { MapTerritory } from '@/features/territories/types';
import type { BattleResult, BattleState } from '@/features/battles/battleRules';
import { battleUnavailableCopy } from '@/features/battles/battleRules';
import { battleRepository } from '@/services/backend/battleRepository';
import { territoryRepository } from '@/services/backend/territoryRepository';
import { explorationRepository } from '@/services/backend/explorationRepository';
import { useAuth } from '@/features/auth/AuthContext';
import { colors } from '@/theme';
import { territoryStatusLabel } from './mapVisuals';

export function TerritoryCard({ territory, onClose }: { territory: MapTerritory; onClose: () => void }) {
  const entrance = useRef(new Animated.Value(0)).current;
  const {refreshPlayer}=useAuth();
  const[state,setState]=useState<BattleState|null>(null);const[modal,setModal]=useState(false);const[result,setResult]=useState<BattleResult|null>(null);const[busy,setBusy]=useState(false);
  useEffect(() => { Animated.timing(entrance, { duration: 180, toValue: 1, useNativeDriver: true }).start(); }, [entrance]);
  const own = territory.status === 'owned';
  useEffect(()=>{setState(null);setResult(null);if(!own&&territory.ownerUserId)void battleRepository.getState(territory.id).then(setState).catch(()=>setState(null))},[own,territory.id,territory.ownerUserId]);
  const delta = Math.max(0, territory.ownerInfluencePoints - territory.myInfluencePoints + 1);const unavailable=state?battleUnavailableCopy(state):null;
  const battle=async()=>{setBusy(true);try{const next=await battleRepository.start(territory.id);setResult(next);await Promise.all([refreshPlayer(),explorationRepository.refresh()]);territoryRepository.invalidate();}finally{setBusy(false)}};
  return <Animated.View style={[styles.card, { opacity: entrance, transform: [{ translateY: entrance.interpolate({ inputRange: [0, 1], outputRange: [16, 0] }) }] }] }>
    <View style={styles.heading}><View><Text style={styles.eyebrow}>{own ? 'YOUR TERRITORY' : 'TERRITORY INTEL'}</Text><Text style={styles.title}>{territory.name}</Text><Text style={styles.subtitle}>{territory.ownerDisplayName ? `Led by ${territory.ownerDisplayName}` : 'No current leader'}</Text></View><Pressable accessibilityLabel="Close territory details" onPress={onClose} style={styles.close}><Ionicons name="close" color={colors.muted} size={20} /></Pressable></View>
    <View style={styles.influenceRow}><Stat label="YOUR INFLUENCE" value={`${territory.myInfluencePoints}`} /><View style={styles.divider}/><Stat label="LEADER INFLUENCE" value={`${territory.ownerInfluencePoints}`} /></View>
    <View style={styles.secondary}><Text style={styles.secondaryText}>{Math.round(territory.controlPercentage)}% CONTROL</Text><Text style={styles.secondaryDot}>•</Text><Text style={styles.secondaryText}>{territory.totalInfluencePoints} TOTAL INFLUENCE</Text><Text style={styles.secondaryDot}>•</Text><Text style={styles.status}>{territoryStatusLabel(territory.status)}</Text></View>
    {!own && territory.ownerUserId ? <Text style={styles.delta}>{delta} more influence {delta === 1 ? 'point' : 'points'} needed to take the lead</Text> : null}
    {!own&&territory.ownerUserId?<View style={styles.battleRow}>{state?.eligible?<Pressable accessibilityRole="button" onPress={()=>setModal(true)} style={styles.battleButton}><Ionicons name="flash" size={14} color={colors.background}/><Text style={styles.battleButtonText}>BATTLE</Text></Pressable>:unavailable?<View><Text style={styles.unavailableTitle}>{unavailable.title}</Text><Text style={styles.unavailableDetail}>{unavailable.detail}</Text></View>:<ActivityIndicator color={colors.gold}/>}</View>:null}
    {__DEV__ && <Text style={styles.debug}>{territory.source.toUpperCase()} · {territory.geometryType} · ATOMIC ZONE</Text>}
    <Modal animationType="fade" transparent visible={modal} onRequestClose={()=>setModal(false)}><View style={styles.scrim}><View style={styles.modal}>{result?<><Text style={styles.modalEyebrow}>{result.result==='captured'?'TERRITORY CAPTURED':result.result==='contested'?'TERRITORY CONTESTED':'PRESSURE APPLIED'}</Text><Text style={styles.modalTitle}>{result.territoryName}</Text><Text style={styles.resultLine}>+{result.influenceAwarded} Influence</Text><Text style={styles.costLine}>-{result.energySpent} Energy</Text><Pressable style={styles.confirm} onPress={()=>{setModal(false);onClose()}}><Text style={styles.confirmText}>DONE</Text></Pressable></>:<><Text style={styles.modalEyebrow}>TERRITORY</Text><Text style={styles.modalTitle}>{territory.name}</Text><View style={styles.confirmStats}><Stat label="YOUR INFLUENCE" value={String(state?.myInfluence??0)}/><Stat label="RIVAL INFLUENCE" value={String(state?.leaderInfluence??0)}/><Stat label="BATTLE PRESSURE" value={`+${state?.influenceReward??0}`}/><Stat label="ENERGY COST" value={String(state?.energyCost??0)}/></View><Pressable disabled={busy} style={styles.confirm} onPress={()=>void battle()}>{busy?<ActivityIndicator color={colors.background}/>:<Text style={styles.confirmText}>CONFIRM BATTLE</Text>}</Pressable><Pressable disabled={busy} onPress={()=>setModal(false)}><Text style={styles.cancel}>CANCEL</Text></Pressable></>}</View></View></Modal>
  </Animated.View>;
}
function Stat({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <View style={styles.stat}><Text style={styles.label}>{label}</Text><Text numberOfLines={1} style={[styles.value, accent && styles.accent]}>{value}</Text></View>; }
const styles = StyleSheet.create({ card: { position: 'absolute', left: 12, right: 12, bottom: 12, padding: 16, borderRadius: 20, backgroundColor: colors.mapOverlay, borderWidth: 1, borderColor: '#52665F' }, heading: { flexDirection: 'row', justifyContent: 'space-between' }, eyebrow: { color: colors.lime, fontSize: 8, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 2 }, subtitle: { color: colors.muted, fontSize: 10, marginTop: 3 }, close: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#FFFFFF0B', alignItems: 'center', justifyContent: 'center' }, influenceRow:{flexDirection:'row',alignItems:'center',marginTop:15},divider:{width:1,height:30,backgroundColor:colors.border,marginHorizontal:18},secondary:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:6,marginTop:11},secondaryText:{color:colors.muted,fontSize:9,fontWeight:'700'},secondaryDot:{color:colors.border},status:{color:colors.gold,fontSize:9,fontWeight:'900'}, stat: { flexShrink:1 }, label: { color: colors.muted, fontSize: 7, fontWeight: '900' }, value: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 2 }, accent: { color: colors.gold }, delta: { color: colors.lime, fontSize: 10, fontWeight: '800', marginTop: 12 }, debug: { color: colors.muted, fontSize: 7, marginTop: 10 },battleRow:{marginTop:12,paddingTop:11,borderTopWidth:1,borderTopColor:colors.border},battleButton:{height:42,borderRadius:11,backgroundColor:colors.gold,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},battleButtonText:{color:colors.background,fontWeight:'900',letterSpacing:1.3},unavailableTitle:{color:colors.gold,fontSize:9,fontWeight:'900',letterSpacing:1},unavailableDetail:{color:colors.muted,fontSize:9,marginTop:3},scrim:{flex:1,justifyContent:'flex-end',backgroundColor:'#00000099'},modal:{padding:22,paddingBottom:34,borderTopLeftRadius:24,borderTopRightRadius:24,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},modalEyebrow:{color:colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.5},modalTitle:{color:colors.text,fontSize:23,fontWeight:'900',marginTop:5},confirmStats:{flexDirection:'row',flexWrap:'wrap',rowGap:18,marginTop:22},confirm:{height:46,borderRadius:13,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center',marginTop:22},confirmText:{color:colors.background,fontWeight:'900'},cancel:{color:colors.muted,textAlign:'center',fontWeight:'800',paddingTop:16},resultLine:{color:colors.lime,fontSize:17,fontWeight:'900',marginTop:22},costLine:{color:colors.gold,fontSize:17,fontWeight:'900',marginTop:5} });
