import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { usePois } from '@/features/poi/PoiContext';
import { TRAINING_GROUND_XP_MULTIPLIER } from '@/features/poi/config';
import type { LeaderboardEntry } from '@/features/poi/arenaRanking';
import type { ArenaWorkoutContribution } from '@/services/storage/arenaRepository';
import { arenaRepository } from '@/services/storage/arenaRepository';
import { colors } from '@/theme';

export default function PoiDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { presences } = usePois();
  const presence = presences.find((item) => item.poi.id === id);
  const [leaders, setLeaders] = useState<LeaderboardEntry[]>([]); const [recent, setRecent] = useState<ArenaWorkoutContribution[]>([]);
  useEffect(() => { if (!id) return; const refresh = () => { void arenaRepository.getLeaderboard(id).then(setLeaders); void arenaRepository.getRecentActivity(id).then(setRecent); }; refresh(); return arenaRepository.subscribe(refresh); }, [id]);
  if (!presence) return <View style={styles.screen}><Text style={styles.empty}>POI unavailable. Return to the map to discover local POIs.</Text></View>;
  const active = presence.status !== 'outside'; const player = leaders.find((item) => item.isPlayer);
  return <ScrollView contentContainerStyle={styles.screen}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" color={colors.text} size={20} /></Pressable><Text style={styles.eyebrow}>{presence.poi.type === 'arena' ? 'ARENA' : 'TRAINING GROUND'}</Text><Text style={styles.title}>{presence.poi.name}</Text><Text style={active ? styles.active : styles.outside}>{active ? 'INSIDE · ACTIVE' : 'OUTSIDE'}</Text><Text style={styles.distance}>{Math.round(presence.distanceMeters)} m away</Text>
    {presence.poi.type === 'training_ground' ? <View style={styles.panel}><Text style={styles.heading}>OUTDOOR BOOST</Text><Text style={styles.boost}>+{Math.round((TRAINING_GROUND_XP_MULTIPLIER - 1) * 100)}% XP</Text><Text style={styles.copy}>Applies only to valid distance earned here during an active outdoor workout.</Text></View> : <><View style={styles.summary}><Value label="WEEKLY RANK" value={`#${player?.rank ?? leaders.length}`} /><Value label="YOUR POINTS" value={(player?.points ?? 0).toLocaleString()} /><Value label="COMPETITORS" value={`${leaders.length}`} /></View><Text style={styles.heading}>WEEKLY LEADERBOARD</Text><View style={styles.panel}>{leaders.map((entry) => <View key={entry.id} style={[styles.row, entry.isPlayer && styles.player]}><Text style={styles.rank}>{entry.rank}</Text><Text style={styles.name}>{entry.name}</Text><Text style={styles.points}>{entry.points.toLocaleString()}</Text></View>)}</View><Text style={styles.heading}>RECENT ARENA ACTIVITY</Text><View style={styles.panel}>{recent.length ? recent.map((item) => <View key={item.id} style={styles.row}><Text style={styles.name}>{new Date(item.completedAt).toLocaleDateString()}</Text><Text style={styles.points}>+{item.points}</Text></View>) : <Text style={styles.copy}>No Arena workouts yet.</Text>}</View></>}
  </ScrollView>;
}
function Value({ label, value }: { label: string; value: string }) { return <View style={styles.value}><Text style={styles.valueNumber}>{value}</Text><Text style={styles.valueLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flexGrow: 1, backgroundColor: colors.background, padding: 20, paddingTop: 54 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginBottom: 25 }, eyebrow: { color: colors.violet, fontSize: 10, fontWeight: '900', letterSpacing: 2 }, title: { color: colors.text, fontSize: 34, fontWeight: '900', marginTop: 4 }, active: { color: colors.lime, fontSize: 12, fontWeight: '900', marginTop: 10 }, outside: { color: colors.muted, fontSize: 12, fontWeight: '900', marginTop: 10 }, distance: { color: colors.muted, marginTop: 4 }, summary: { flexDirection: 'row', gap: 6, marginTop: 24 }, value: { flex: 1, paddingVertical: 15, alignItems: 'center', backgroundColor: colors.surface, borderRadius: 15 }, valueNumber: { color: colors.text, fontSize: 18, fontWeight: '900' }, valueLabel: { color: colors.muted, fontSize: 7, marginTop: 4, fontWeight: '800' }, heading: { color: colors.muted, fontSize: 9, fontWeight: '900', letterSpacing: 1.5, marginTop: 25, marginBottom: 8 }, panel: { backgroundColor: colors.surface, borderRadius: 18, padding: 14 }, row: { minHeight: 46, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.border }, player: { backgroundColor: '#B7E85A12' }, rank: { color: colors.muted, width: 28 }, name: { color: colors.text, flex: 1, fontWeight: '700' }, points: { color: colors.cyan, fontWeight: '900' }, boost: { color: colors.lime, fontSize: 42, fontWeight: '900' }, copy: { color: colors.muted, lineHeight: 19, paddingVertical: 8 }, empty: { color: colors.muted, marginTop: 100, textAlign: 'center' } });
