import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '@/features/auth/AuthContext';
import { activeActivityRepository } from '@/services/storage/activeActivityRepository';
import { accountRepository } from '@/services/backend/accountRepository';
import { colors } from '@/theme';
import { targetRepository } from '@/features/targets/targetRepository';

export default function DeleteAccount(){const{user}=useAuth();const[confirmed,setConfirmed]=useState(false);const[phrase,setPhrase]=useState('');const[busy,setBusy]=useState(false);
 const begin=async()=>{if(await activeActivityRepository.get(user?.id)){Alert.alert('Activity unresolved','Finish or discard your current activity before deleting your account.');return;}Alert.alert('DELETE YOUR ACCOUNT?','This permanently removes your Ruqest account and cannot be undone.',[{text:'CANCEL',style:'cancel'},{text:'CONTINUE',style:'destructive',onPress:()=>setConfirmed(true)}]);};
 const remove=async()=>{if(!user||phrase!=='DELETE')return;setBusy(true);try{await accountRepository.deleteCurrentAccount(user.id);await targetRepository.clearDeletedUser(user.id);router.replace('/');}catch(error){Alert.alert('Deletion failed',error instanceof Error?error.message:'Try again.');setBusy(false);}};
 return <View style={s.screen}><Text style={s.eyebrow}>DANGER ZONE</Text><Text style={s.title}>Delete account</Text><Text style={s.copy}>Permanently erase your Ruqest identity, progress, and account. This cannot be undone.</Text>{confirmed?<><Text style={s.label}>TYPE DELETE TO CONFIRM</Text><TextInput autoCapitalize="characters" editable={!busy} value={phrase} onChangeText={setPhrase} style={s.input}/><Pressable disabled={busy||phrase!=='DELETE'} onPress={()=>void remove()} style={[s.delete,(busy||phrase!=='DELETE')&&s.disabled]}>{busy?<ActivityIndicator color={colors.text}/>:<Text style={s.deleteText}>PERMANENTLY DELETE ACCOUNT</Text>}</Pressable></>:<Pressable onPress={()=>void begin()} style={s.delete}><Text style={s.deleteText}>DELETE ACCOUNT</Text></Pressable>}<Pressable disabled={busy} onPress={()=>router.back()}><Text style={s.cancel}>CANCEL</Text></Pressable></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background,padding:24,paddingTop:64},eyebrow:{color:colors.danger,fontWeight:'900',letterSpacing:2,fontSize:10},title:{color:colors.text,fontWeight:'900',fontSize:30,marginTop:10},copy:{color:colors.muted,lineHeight:21,marginTop:14},label:{color:colors.danger,fontWeight:'900',fontSize:10,marginTop:30},input:{height:50,borderWidth:1,borderColor:colors.danger,color:colors.text,borderRadius:12,paddingHorizontal:14,marginTop:8},delete:{height:52,backgroundColor:colors.danger,borderRadius:13,alignItems:'center',justifyContent:'center',marginTop:24},disabled:{opacity:.35},deleteText:{color:colors.text,fontWeight:'900'},cancel:{textAlign:'center',color:colors.muted,fontWeight:'900',padding:20}});
