import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
// eslint-disable-next-line import/no-unresolved -- installed by Expo in native builds.
import * as ImagePicker from 'expo-image-picker';
import { router } from 'expo-router';
import { ProfileForm } from '@/components/profile/ProfileForm';
import { Avatar } from '@/components/profile/Avatar';
import { useAuth } from '@/features/auth/AuthContext';
import { isValidBio, isValidUsername } from '@/features/profile/profileRules';
import { avatarRepository, profileRepository, type ProfileDraft } from '@/services/backend/profileRepository';
import { colors } from '@/theme';

export default function EditProfile(){
 const{profile,user,refreshPlayer}=useAuth();const[value,setValue]=useState<ProfileDraft>({username:profile?.username??'',displayName:profile?.display_name??'',avatarUrl:profile?.avatar_url??null,bio:profile?.bio??'',preferredActivities:profile?.preferred_activities??[],city:profile?.city??'',region:profile?.region??''});const[saving,setSaving]=useState(false);if(!profile||!user)return null;
 const changePhoto=async()=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Photo access needed','Allow photo library access to choose a profile photo.');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.82});if(result.canceled)return;setSaving(true);try{const url=await avatarRepository.replace(user.id,value.avatarUrl,result.assets[0]!);setValue(current=>({...current,avatarUrl:url}));await refreshPlayer();}catch(error){Alert.alert('Photo update failed',error instanceof Error?error.message:'Try again.')}finally{setSaving(false)}};
 const removePhoto=async()=>{setSaving(true);try{await avatarRepository.remove(user.id,value.avatarUrl);setValue(current=>({...current,avatarUrl:null}));await refreshPlayer();}catch(error){Alert.alert('Could not remove photo',error instanceof Error?error.message:'Try again.')}finally{setSaving(false)}};
 const save=async()=>{if(!isValidUsername(value.username)||!isValidBio(value.bio)||!value.displayName.trim()){Alert.alert('Check your profile','Use a valid username, display name, and bio up to 160 characters.');return;}setSaving(true);try{await profileRepository.update(value);await refreshPlayer();router.back();}catch(error){Alert.alert('Update failed',error instanceof Error?error.message:'Try again.')}finally{setSaving(false)}};
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.screen}><Text style={s.eyebrow}>PLAYER LOADOUT</Text><Text style={s.title}>Edit profile</Text><Avatar name={value.displayName} url={value.avatarUrl}/><View style={s.avatarActions}><Pressable disabled={saving} onPress={()=>void changePhoto()}><Text style={s.photo}>CHANGE PHOTO</Text></Pressable>{value.avatarUrl?<Pressable disabled={saving} onPress={()=>void removePhoto()}><Text style={s.remove}>REMOVE PHOTO</Text></Pressable>:null}</View><ProfileForm value={value} onChange={setValue}/><Pressable disabled={saving} accessibilityLabel="Save profile" onPress={()=>void save()} style={s.button}>{saving?<ActivityIndicator color={colors.background}/>:<Text style={s.buttonText}>SAVE PLAYER</Text>}</Pressable><Pressable onPress={()=>router.back()}><Text style={s.cancel}>CANCEL</Text></Pressable></ScrollView>;
}
const s=StyleSheet.create({screen:{padding:22,paddingTop:54,paddingBottom:40,backgroundColor:colors.background,alignItems:'stretch'},eyebrow:{color:colors.cyan,fontSize:10,fontWeight:'900',letterSpacing:2},title:{color:colors.text,fontSize:29,fontWeight:'900',marginVertical:14},avatarActions:{flexDirection:'row',justifyContent:'center',gap:22,marginVertical:14},photo:{color:colors.cyan,fontSize:11,fontWeight:'900'},remove:{color:colors.danger,fontSize:11,fontWeight:'900'},button:{height:52,borderRadius:14,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center',marginTop:25},buttonText:{fontWeight:'900',color:colors.background},cancel:{textAlign:'center',color:colors.muted,fontWeight:'900',padding:18}});
