export const TERRITORY_RADIUS_METERS=190; export const INFLUENCE_METERS_PER_POINT=100; const EARTH_RADIUS_METERS=6_378_137; const MAX_POINTS=20_000; const MAX_DURATION_MS=24*60*60*1000; const SPEED_LIMIT={walking:12,running:18,cycling:45} as const;
export type OutdoorType=keyof typeof SPEED_LIMIT; export interface RoutePoint{latitude:number;longitude:number;timestamp:string;accuracy?:number} export interface SubmitActivity{clientActivityId:string;type:OutdoorType;startedAt:string;endedAt:string;acceptedRoutePoints:RoutePoint[]}
const rad=(v:number)=>v*Math.PI/180; const deg=(v:number)=>v*180/Math.PI;
export function distanceMeters(a:RoutePoint,b:RoutePoint){const dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 6_371_000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function roundAxial(q:number,r:number){let rq=Math.round(q),rr=Math.round(r);const rs=Math.round(-q-r),qd=Math.abs(rq-q),rd=Math.abs(rr-r),sd=Math.abs(rs+q+r);if(qd>rd&&qd>sd)rq=-rr-rs;else if(rd>sd)rr=-rq-rs;return{q:rq,r:rr};}
export function territoryCoordinatesAt(latitude:number,longitude:number){const lat=Math.max(-85,Math.min(85,latitude));const x=EARTH_RADIUS_METERS*rad(longitude),y=EARTH_RADIUS_METERS*Math.log(Math.tan(Math.PI/4+rad(lat)/2));return roundAxial((Math.sqrt(3)/3*x-y/3)/TERRITORY_RADIUS_METERS,(2*y/3)/TERRITORY_RADIUS_METERS);}
export const territoryId=(q:number,r:number)=>`local-${q}-${r}`; const territoryName=(q:number,r:number)=>`Jardim #${1800+Math.abs((q*31+r*17)%700)}`;
function unproject(x:number,y:number){return[deg(x/EARTH_RADIUS_METERS),deg(2*Math.atan(Math.exp(y/EARTH_RADIUS_METERS))-Math.PI/2)];}
export function territoryShape(q:number,r:number){const x=TERRITORY_RADIUS_METERS*Math.sqrt(3)*(q+r/2),y=TERRITORY_RADIUS_METERS*1.5*r;const ring=Array.from({length:6},(_,i)=>{const a=rad(60*i-30);return unproject(x+TERRITORY_RADIUS_METERS*Math.cos(a),y+TERRITORY_RADIUS_METERS*Math.sin(a));});ring.push(ring[0]!);return{id:territoryId(q,r),q,r,name:territoryName(q,r),center:{type:'Point',coordinates:unproject(x,y)},geometry:{type:'Polygon',coordinates:[ring]}};}
export function validateAndCompute(input:unknown){if(!input||typeof input!=='object')throw new Error('Invalid request');const body=input as Partial<SubmitActivity>;if(typeof body.clientActivityId!=='string'||!/^[A-Za-z0-9._:-]{1,128}$/.test(body.clientActivityId))throw new Error('Invalid activity ID');if(!body.type||!(body.type in SPEED_LIMIT))throw new Error('Invalid activity type');const start=Date.parse(body.startedAt??''),end=Date.parse(body.endedAt??'');if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>MAX_DURATION_MS)throw new Error('Invalid activity time range');const points=body.acceptedRoutePoints;if(!Array.isArray(points)||points.length<2||points.length>MAX_POINTS)throw new Error('Invalid route point count');let distance=0;const impacts=new Map<string,{q:number;r:number;distanceMeters:number}>();for(let i=0;i<points.length;i++){const p=points[i]!;if(!Number.isFinite(p.latitude)||!Number.isFinite(p.longitude)||p.latitude<-90||p.latitude>90||p.longitude<-180||p.longitude>180||p.accuracy!==undefined&&(!Number.isFinite(p.accuracy)||p.accuracy<0||p.accuracy>100))throw new Error('Invalid route coordinate');const time=Date.parse(p.timestamp);if(!Number.isFinite(time)||time<start||time>end||(i&&time<=Date.parse(points[i-1]!.timestamp)))throw new Error('Route timestamps must be monotonic');if(i){const previous=points[i-1]!,segment=distanceMeters(previous,p),seconds=(time-Date.parse(previous.timestamp))/1000;if(segment/seconds>SPEED_LIMIT[body.type])throw new Error('Impossible route speed');distance+=segment;
// Subdivide before midpoint classification so a long accepted segment crossing
// cells is allocated across every traversed atomic territory, not just one cell.
const pieces=Math.max(1,Math.ceil(segment/20)),pieceDistance=segment/pieces;for(let piece=0;piece<pieces;piece++){const ratio=(piece+.5)/pieces,midLat=previous.latitude+(p.latitude-previous.latitude)*ratio,midLon=previous.longitude+(p.longitude-previous.longitude)*ratio,{q,r}=territoryCoordinatesAt(midLat,midLon),id=territoryId(q,r),current=impacts.get(id)??{q,r,distanceMeters:0};current.distanceMeters+=pieceDistance;impacts.set(id,current);}}}
const impactList=[...impacts].map(([territoryId,v])=>({territoryId,distanceMeters:v.distanceMeters,influenceEarned:Math.floor(v.distanceMeters/INFLUENCE_METERS_PER_POINT)}));return{clientActivityId:body.clientActivityId,type:body.type,startedAt:new Date(start).toISOString(),endedAt:new Date(end).toISOString(),distanceMeters:distance,xp:Math.floor(distance/1000*100),energy:Math.floor(distance/1000*24),route:{type:'LineString',coordinates:points.map(p=>[p.longitude,p.latitude])},territories:[...impacts.values()].map(v=>territoryShape(v.q,v.r)),impacts:impactList};}
