-- PLAYER IDENTITY V1. Existing users intentionally re-enter onboarding.
alter table public.profiles add column if not exists bio text, add column if not exists preferred_activities text[] not null default '{}', add column if not exists city text, add column if not exists region text, add column if not exists onboarding_completed boolean not null default false;
create function public.valid_activity_preferences(values_to_check text[]) returns boolean language sql immutable set search_path='' as $$select values_to_check <@ array['walking','running','cycling','indoor']::text[] and cardinality(values_to_check)=cardinality(array(select distinct unnest(values_to_check)))$$;
alter table public.profiles add constraint profiles_bio_length check (bio is null or char_length(bio)<=160), add constraint profiles_city_length check(city is null or char_length(city)<=80), add constraint profiles_region_length check(region is null or char_length(region)<=80), add constraint profiles_preferred_activities_valid check (public.valid_activity_preferences(preferred_activities));

create table public.profile_privacy(user_id uuid primary key references auth.users(id) on delete cascade,profile_visibility text not null default 'public' check(profile_visibility in('public','friends','private')),activity_visibility text not null default 'friends' check(activity_visibility in('public','friends','private')),show_level boolean not null default true,show_stats boolean not null default true,show_territories boolean not null default true,show_achievements boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.profile_privacy(user_id) select id from public.profiles on conflict do nothing;
create table public.friendships(id uuid primary key default extensions.gen_random_uuid(),requester_id uuid not null references auth.users(id) on delete cascade,addressee_id uuid not null references auth.users(id) on delete cascade,status text not null default 'pending' check(status in('pending','accepted','blocked')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(requester_id<>addressee_id));
create unique index friendships_pair_unique on public.friendships(least(requester_id,addressee_id),greatest(requester_id,addressee_id));
create index friendships_requester_idx on public.friendships(requester_id); create index friendships_addressee_idx on public.friendships(addressee_id);
alter table public.profile_privacy enable row level security; alter table public.friendships enable row level security;
create policy "privacy_select_own" on public.profile_privacy for select to authenticated using((select auth.uid())=user_id);
create policy "privacy_update_own" on public.profile_privacy for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
-- Friendship rows are deliberately RPC-only so state transitions cannot be forged.
revoke all on public.profile_privacy,public.friendships from anon; revoke all on public.friendships from authenticated;
grant select on public.profile_privacy to authenticated; grant update(profile_visibility,activity_visibility,show_level,show_stats,show_territories,show_achievements) on public.profile_privacy to authenticated;
grant update(username,display_name,avatar_url,bio,preferred_activities,city,region) on public.profiles to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,username,display_name,avatar_url) values(new.id,'player_'||substr(replace(new.id::text,'-',''),1,8),left(coalesce(nullif(new.raw_user_meta_data->>'full_name',''),nullif(new.raw_user_meta_data->>'name',''),'Player'),60),left(coalesce(new.raw_user_meta_data->>'avatar_url',new.raw_user_meta_data->>'picture'),2048)); insert into public.player_progress(user_id) values(new.id); insert into public.profile_privacy(user_id) values(new.id); return new; end $$;

create function public.is_username_available(candidate text) returns boolean language sql stable security definer set search_path='' as $$select (select auth.uid()) is not null and candidate ~ '^[A-Za-z0-9_]{3,30}$' and not exists(select 1 from public.profiles where lower(username)=lower(candidate) and id<>(select auth.uid()))$$;
create unique index profiles_username_lower_unique on public.profiles(lower(username));

create function public.complete_player_onboarding(p_username text,p_display_name text,p_avatar_url text,p_bio text,p_preferred_activities text[],p_city text,p_region text,p_profile_visibility text,p_activity_visibility text,p_show_level boolean,p_show_stats boolean,p_show_territories boolean,p_show_achievements boolean) returns void language plpgsql security definer set search_path='' as $$declare u uuid:=(select auth.uid());begin if u is null then raise exception 'authentication required'; end if; update public.profiles set username=p_username,display_name=p_display_name,avatar_url=nullif(p_avatar_url,''),bio=nullif(p_bio,''),preferred_activities=p_preferred_activities,city=nullif(p_city,''),region=nullif(p_region,''),onboarding_completed=true,updated_at=now() where id=u; if not found then raise exception 'profile missing';end if; insert into public.profile_privacy(user_id,profile_visibility,activity_visibility,show_level,show_stats,show_territories,show_achievements) values(u,p_profile_visibility,p_activity_visibility,p_show_level,p_show_stats,p_show_territories,p_show_achievements) on conflict(user_id) do update set profile_visibility=excluded.profile_visibility,activity_visibility=excluded.activity_visibility,show_level=excluded.show_level,show_stats=excluded.show_stats,show_territories=excluded.show_territories,show_achievements=excluded.show_achievements,updated_at=now(); exception when unique_violation then raise exception using errcode='23505',message='username unavailable';end$$;
create function public.update_player_profile(p_username text,p_display_name text,p_avatar_url text,p_bio text,p_preferred_activities text[],p_city text,p_region text) returns void language plpgsql security definer set search_path='' as $$begin update public.profiles set username=p_username,display_name=p_display_name,avatar_url=nullif(p_avatar_url,''),bio=nullif(p_bio,''),preferred_activities=p_preferred_activities,city=nullif(p_city,''),region=nullif(p_region,''),updated_at=now() where id=(select auth.uid()); if not found then raise exception 'profile missing';end if; exception when unique_violation then raise exception using errcode='23505',message='username unavailable';end$$;

create function public.get_player_profile(target_user_id uuid) returns table(id uuid,username text,display_name text,avatar_url text,bio text,preferred_activities text[],city text,region text,level integer,xp bigint,total_distance double precision,total_activities bigint,territories_count bigint,total_influence bigint,relationship_status text) language sql stable security definer set search_path='' as $$
with rel as(select * from public.friendships where (requester_id=(select auth.uid()) and addressee_id=target_user_id) or(addressee_id=(select auth.uid()) and requester_id=target_user_id) limit 1), access as(select (select auth.uid())=target_user_id self,coalesce((select status='accepted' from rel),false) friend,coalesce((select status='blocked' from rel),false) blocked), stats as(select count(*) n,coalesce(sum(distance_meters),0)::double precision d from public.activities where user_id=target_user_id), inf as(select count(*) filter(where influence_points>0) c,coalesce(sum(influence_points),0) i from public.territory_influence where user_id=target_user_id)
select p.id,p.username,case when a.self or(not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then p.display_name end,p.avatar_url,case when a.self or(not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then p.bio end,case when a.self or(not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then p.preferred_activities end,case when a.self or(not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then p.city end,case when a.self or(not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then p.region end,case when v.show_level or a.self then pg.level end,case when (a.self or (v.show_stats and not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend)))) then pg.xp end,case when a.self or(v.show_stats and not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then s.d end,case when a.self or(v.show_stats and not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then s.n end,case when a.self or(v.show_territories and not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then i.c end,case when a.self or(v.show_territories and not a.blocked and(v.profile_visibility='public' or(v.profile_visibility='friends' and a.friend))) then i.i end,case when a.self then 'self' when exists(select 1 from rel where status='blocked') then 'blocked' when exists(select 1 from rel where status='accepted') then 'friends' when exists(select 1 from rel where status='pending' and requester_id=(select auth.uid())) then 'pending_sent' when exists(select 1 from rel where status='pending') then 'pending_received' else 'none' end from public.profiles p join public.profile_privacy v on v.user_id=p.id left join public.player_progress pg on pg.user_id=p.id cross join access a cross join stats s cross join inf i where p.id=target_user_id and (select auth.uid()) is not null;$$;

create function public.search_players(search_query text) returns table(id uuid,username text,display_name text,avatar_url text,level integer) language sql stable security definer set search_path='' as $$select p.id,p.username,case when v.profile_visibility='public' then p.display_name end,p.avatar_url,case when v.show_level then g.level end from public.profiles p join public.profile_privacy v on v.user_id=p.id left join public.player_progress g on g.user_id=p.id where (select auth.uid()) is not null and char_length(trim(search_query))>=3 and p.id<>(select auth.uid()) and (p.username ilike '%'||trim(search_query)||'%' or p.display_name ilike '%'||trim(search_query)||'%') and not exists(select 1 from public.friendships f where f.status='blocked' and ((f.requester_id=(select auth.uid()) and f.addressee_id=p.id)or(f.addressee_id=(select auth.uid()) and f.requester_id=p.id))) order by case when lower(p.username)=lower(trim(search_query)) then 0 else 1 end,p.username limit 20$$;

create function public.send_friend_request(target_user_id uuid) returns void language plpgsql security definer set search_path='' as $$begin if target_user_id=(select auth.uid()) then raise exception 'cannot friend self';end if;insert into public.friendships(requester_id,addressee_id)values((select auth.uid()),target_user_id);end$$;
create function public.accept_friend_request(target_user_id uuid) returns void language plpgsql security definer set search_path='' as $$begin update public.friendships set status='accepted',updated_at=now() where requester_id=target_user_id and addressee_id=(select auth.uid()) and status='pending';if not found then raise exception 'request not found';end if;end$$;
create function public.remove_friend(target_user_id uuid) returns void language plpgsql security definer set search_path='' as $$begin delete from public.friendships where status<>'blocked' and ((requester_id=(select auth.uid()) and addressee_id=target_user_id)or(addressee_id=(select auth.uid()) and requester_id=target_user_id));end$$;
create function public.block_player(target_user_id uuid) returns void language plpgsql security definer set search_path='' as $$begin if target_user_id=(select auth.uid())then raise exception 'cannot block self';end if;delete from public.friendships where (requester_id=(select auth.uid()) and addressee_id=target_user_id)or(addressee_id=(select auth.uid()) and requester_id=target_user_id);insert into public.friendships(requester_id,addressee_id,status)values((select auth.uid()),target_user_id,'blocked');end$$;

-- Public avatar bytes, owner-only writes under <uid>/...; client also enforces 5 MB/images.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('avatars','avatars',true,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=true,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;
create policy "avatar_insert_own" on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "avatar_update_own" on storage.objects for update to authenticated using(bucket_id='avatars' and owner_id=(select auth.uid()::text)) with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "avatar_delete_own" on storage.objects for delete to authenticated using(bucket_id='avatars' and owner_id=(select auth.uid()::text));

revoke all on function public.get_player_profile(uuid),public.search_players(text),public.complete_player_onboarding(text,text,text,text,text[],text,text,text,text,boolean,boolean,boolean,boolean),public.update_player_profile(text,text,text,text,text[],text,text),public.is_username_available(text),public.send_friend_request(uuid),public.accept_friend_request(uuid),public.remove_friend(uuid),public.block_player(uuid) from public,anon;
grant execute on function public.get_player_profile(uuid),public.search_players(text),public.complete_player_onboarding(text,text,text,text,text[],text,text,text,text,boolean,boolean,boolean,boolean),public.update_player_profile(text,text,text,text,text[],text,text),public.is_username_available(text),public.send_friend_request(uuid),public.accept_friend_request(uuid),public.remove_friend(uuid),public.block_player(uuid) to authenticated;
