import { supabase } from '@/lib/supabase';
import { activityRepository, type StoredOutdoorActivity } from '@/services/storage/activityRepository';
import { inventoryRepository } from '@/services/backend/inventoryRepository';
import type { AuthoritativeLootGrant } from '@/features/inventory/lootRules';
import { classifySyncFailure, isCompleteActivityResponse } from '@/features/activity/syncContract';
import { territoryRepository } from './territoryRepository';
import { weeklySummaryRepository } from './weeklySummaryRepository';
import { hasSyncableOutdoorRoute } from '@/features/activity/tracking';
let running=false; let lastAttempt=0; const RETRY_DELAY_MS=30_000;
function payload(activity:StoredOutdoorActivity){return{clientActivityId:activity.clientActivityId,type:activity.type,startedAt:new Date(activity.startedAt).toISOString(),endedAt:new Date(activity.endedAt).toISOString(),acceptedRoutePoints:activity.route.map(({latitude,longitude,timestamp,accuracy,breakBefore})=>({latitude,longitude,timestamp:new Date(timestamp).toISOString(),accuracy,breakBefore}))};}
export const activitySyncService={
 async syncPending(ownerUserId:string,force=false){if(running||(!force&&Date.now()-lastAttempt<RETRY_DELAY_MS))return;running=true;lastAttempt=Date.now();try{await activityRepository.recoverInterruptedSync();for(const activity of await activityRepository.pending(ownerUserId)){if(activity.ownerUserId!==ownerUserId)continue;if(!hasSyncableOutdoorRoute(activity.route)){await activityRepository.markFailed(activity.id,'INSUFFICIENT_GPS_DATA','Not enough GPS data was recorded to synchronize this activity.');continue;}await activityRepository.markSyncing(activity.id);try{const{data,error}=await supabase.functions.invoke('complete-activity',{body:payload(activity)});if(error)throw error;if(!isCompleteActivityResponse(data))throw new Error('Backend contract mismatch: malformed activity response');await activityRepository.markSynced(activity.id,{activityId:data.activityId,distanceMeters:data.distanceMeters,xpEarned:data.xpEarned,energyEarned:data.energyEarned,influenceEarned:data.influenceEarned,territoryImpacts:data.territoryImpacts as StoredOutdoorActivity['traversals'],loot:data.loot as AuthoritativeLootGrant[]});territoryRepository.invalidate();if(__DEV__)console.info('[Activity sync] Authoritative result.',{distanceMeters:data.distanceMeters,influenceEarned:data.influenceEarned,territoryCount:data.territoryImpacts.length});try{await Promise.all([inventoryRepository.refresh(ownerUserId),weeklySummaryRepository.refresh()]);}catch{/* Activity is safely synced; cached inventory can refresh later. */}}catch(error){const failure=classifySyncFailure(error);await activityRepository.markFailed(activity.id,failure.code,failure.message);if(failure.global)break;}}}finally{running=false;}},
};
